export const messages = {
  ar: {
    appName:'الكرنه', home:'الرئيسية', sales:'المبيعات', inventory:'المخزون', parties:'الحسابات', more:'المزيد',
    newSale:'بيع جديد', purchases:'المشتريات', expenses:'المصاريف', records:'سجل الفواتير', products:'المنتجات', warehouses:'المخازن', stock:'الجرد', transfer:'تحويل', adjustment:'تصحيح المخزون', customers:'العملاء', suppliers:'الموردون', accounts:'وسائل الدفع', reports:'التقارير', settings:'الإعدادات',
    todaySales:'مبيعات اليوم', todayProfit:'ربح اليوم', todayExpenses:'مصروف اليوم', receivable:'لنا عند العملاء', payable:'علينا للموردين', inventoryValue:'قيمة المخزون', lowStock:'مخزون منخفض',
    search:'بحث', add:'إضافة', save:'حفظ', cancel:'إلغاء', confirm:'تأكيد', delete:'حذف', restore:'استعادة', edit:'تعديل', amount:'المبلغ', quantity:'الكمية', price:'السعر', total:'الإجمالي', paid:'المدفوع', due:'المتبقي', date:'التاريخ', note:'ملاحظة', name:'الاسم', phone:'الهاتف', barcode:'الباركود', purchasePrice:'سعر الشراء', salePrice:'سعر البيع', wholesalePrice:'سعر الجملة', expiryDate:'تاريخ الصلاحية', warehouse:'المخزن', paymentMethod:'وسيلة الدفع', customer:'العميل', supplier:'المورد', directSale:'بيع مباشر', directPurchase:'شراء مباشر', onCredit:'آجل', retail:'تجزئة', wholesale:'جملة',
    noData:'لا توجد بيانات بعد', noResults:'لا توجد نتائج', loading:'جارٍ التحميل…', tryAgain:'إعادة المحاولة', success:'تمت العملية بنجاح', error:'تعذر إتمام العملية', language:'اللغة', arabic:'العربية', french:'الفرنسية', dataBackup:'البيانات والنسخ الاحتياطي', exportBackup:'تصدير نسخة احتياطية', importBackup:'استعادة نسخة احتياطية',
    receive:'استلام', pay:'دفع', balance:'الرصيد', openingBalance:'رصيد البداية', from:'من', to:'إلى', reason:'السبب', actualQuantity:'الرصيد الفعلي', createProduct:'منتج جديد', createParty:'حساب جديد', createExpense:'مصروف جديد', completeSale:'إتمام البيع', completePurchase:'إتمام الشراء', addLine:'إضافة منتج', remove:'إزالة', allWarehouses:'كل المخازن', posted:'معتمد', voided:'ملغى',
  },
  fr: {
    appName:'Al Karna', home:'Accueil', sales:'Ventes', inventory:'Stock', parties:'Comptes', more:'Plus',
    newSale:'Nouvelle vente', purchases:'Achats', expenses:'Dépenses', records:'Factures', products:'Produits', warehouses:'Dépôts', stock:'Inventaire', transfer:'Transfert', adjustment:'Correction de stock', customers:'Clients', suppliers:'Fournisseurs', accounts:'Moyens de paiement', reports:'Rapports', settings:'Paramètres',
    todaySales:'Ventes du jour', todayProfit:'Bénéfice du jour', todayExpenses:'Dépenses du jour', receivable:'À recevoir', payable:'À payer', inventoryValue:'Valeur du stock', lowStock:'Stock faible',
    search:'Rechercher', add:'Ajouter', save:'Enregistrer', cancel:'Annuler', confirm:'Confirmer', delete:'Supprimer', restore:'Restaurer', edit:'Modifier', amount:'Montant', quantity:'Quantité', price:'Prix', total:'Total', paid:'Payé', due:'Reste', date:'Date', note:'Note', name:'Nom', phone:'Téléphone', barcode:'Code-barres', purchasePrice:"Prix d'achat", salePrice:'Prix de vente', wholesalePrice:'Prix de gros', expiryDate:'Date de péremption', warehouse:'Dépôt', paymentMethod:'Paiement', customer:'Client', supplier:'Fournisseur', directSale:'Vente directe', directPurchase:'Achat direct', onCredit:'À crédit', retail:'Détail', wholesale:'Gros',
    noData:'Aucune donnée', noResults:'Aucun résultat', loading:'Chargement…', tryAgain:'Réessayer', success:'Opération réussie', error:"Impossible de terminer l'opération", language:'Langue', arabic:'Arabe', french:'Français', dataBackup:'Données et sauvegarde', exportBackup:'Exporter une sauvegarde', importBackup:'Restaurer une sauvegarde',
    receive:'Encaisser', pay:'Payer', balance:'Solde', openingBalance:'Solde initial', from:'De', to:'Vers', reason:'Motif', actualQuantity:'Stock réel', createProduct:'Nouveau produit', createParty:'Nouveau compte', createExpense:'Nouvelle dépense', completeSale:'Valider la vente', completePurchase:"Valider l'achat", addLine:'Ajouter un produit', remove:'Retirer', allWarehouses:'Tous les dépôts', posted:'Validé', voided:'Annulé',
  },
} as const;
export type MessageKey = keyof typeof messages.ar;