import * as Crypto from 'expo-crypto';
import type { SQLiteDatabase } from 'expo-sqlite';
import { assertMoney, assertQuantity, isProductExpired, normalizePartyNet, partyCashDelta, roundLineTotal } from '@/domain/accounting';
import type { PartyType, PricingMode } from '@/domain/types';
import { nextCounter } from '@/db/database';

export class AccountingError extends Error {
  constructor(message: string, readonly code: string = 'invalid') { super(message); this.name = 'AccountingError'; }
}

type Tx = SQLiteDatabase;
type ProductDb = {id:string;name:string;sku:string;piece_cost:number|null;last_purchase_cost:number|null;piece_price:number|null;wholesale_price:number|null;expiry_date:string|null;is_archived:number};
type WarehouseDb = {id:string;name:string;is_sales_default:number;is_archived:number};
type PartyDb = {id:string;name:string;party_type:PartyType;receivable:number;payable:number;net:number};
type AccountDb = {id:string;code:string;name:string;balance:number;opening_balance:number;is_active:number;is_archived:number};
type DocDb = {id:string;number:string;kind:'sale'|'purchase'|'expense';status:string;party_id:string|null;warehouse_id:string|null;payment_method:string|null;total:number;due_total:number;paid_total:number;cash_amount:number;occurred_at:string};
type LineDb = {id:string;product_id:string|null;quantity:number;unit_price:number;line_total:number;cost_at_sale:number|null};

const id = (prefix:string) => `${prefix}-${Crypto.randomUUID()}`;
const now = () => new Date().toISOString();
const today = () => new Date().toISOString().slice(0,10);

async function activeWarehouse(tx:Tx, warehouseId:string) {
  const row=await tx.getFirstAsync<WarehouseDb>('SELECT id,name,is_sales_default,is_archived FROM warehouses WHERE id=? AND is_archived=0',[warehouseId]);
  if(!row) throw new AccountingError('المخزن غير موجود','warehouse_missing');
  return row;
}
async function product(tx:Tx, productId:string, active=true) {
  const row=await tx.getFirstAsync<ProductDb>(`SELECT id,name,sku,piece_cost,last_purchase_cost,piece_price,wholesale_price,expiry_date,is_archived FROM products WHERE id=?${active?' AND is_archived=0':''}`,[productId]);
  if(!row) throw new AccountingError('المنتج غير موجود','product_missing');
  return row;
}
async function party(tx:Tx, partyId:string) {
  const row=await tx.getFirstAsync<PartyDb>('SELECT id,name,party_type,receivable,payable,net FROM parties WHERE id=?',[partyId]);
  if(!row) throw new AccountingError('الحساب غير موجود','party_missing');
  return row;
}
async function account(tx:Tx, accountId:string, active=true) {
  const row=await tx.getFirstAsync<AccountDb>(`SELECT id,code,name,balance,opening_balance,is_active,is_archived FROM payment_accounts WHERE (id=? OR code=?)${active?' AND is_active=1 AND is_archived=0':''}`,[accountId,accountId]);
  if(!row) throw new AccountingError('وسيلة الدفع غير موجودة','account_missing');
  return row;
}
async function stock(tx:Tx, productId:string, warehouseId:string) {
  const row=await tx.getFirstAsync<{quantity:number}>('SELECT quantity FROM product_stocks WHERE product_id=? AND warehouse_id=?',[productId,warehouseId]);
  return Number(row?.quantity??0);
}
async function changeStock(tx:Tx, args:{product:ProductDb;warehouse:WarehouseDb;delta:number;documentId:string;documentNumber:string;movementType:string;occurredAt:string}) {
  const before=await stock(tx,args.product.id,args.warehouse.id); const after=before+args.delta;
  if(after<0) throw new AccountingError(`المخزون غير كافٍ للمنتج ${args.product.name}`,'insufficient_stock');
  await tx.runAsync('INSERT INTO product_stocks(product_id,warehouse_id,quantity) VALUES(?,?,?) ON CONFLICT(product_id,warehouse_id) DO UPDATE SET quantity=excluded.quantity',[args.product.id,args.warehouse.id,after]);
  await tx.runAsync('INSERT INTO stock_movements(id,document_id,document_number,warehouse_id,warehouse_name,product_id,product_name,type,quantity_delta,balance_before,balance_after,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[id('mov'),args.documentId,args.documentNumber,args.warehouse.id,args.warehouse.name,args.product.id,args.product.name,args.movementType,args.delta,before,after,args.occurredAt]);
  return {before,after};
}
async function applyPartyDelta(tx:Tx, partyId:string, delta:number) {
  const p=await party(tx,partyId); const before=p.net; const normalized=normalizePartyNet(before+delta); const stamp=now();
  await tx.runAsync('UPDATE parties SET receivable=?,payable=?,net=?,updated_at=? WHERE id=?',[normalized.receivable,normalized.payable,normalized.net,stamp,partyId]);
  return {before,delta,after:normalized.net,party:p};
}
async function financialMovement(tx:Tx,args:{accountId:string;direction:'in'|'out';amount:number;documentId:string;documentNumber:string;partyId?:string|null;partyName?:string|null;type:string;occurredAt:string;transferId?:string|null;note?:string|null}) {
  if(args.amount===0) return;
  const a=await account(tx,args.accountId); const delta=args.direction==='in'?args.amount:-args.amount; const after=a.balance+delta;
  await tx.runAsync('UPDATE payment_accounts SET balance=?,updated_at=? WHERE id=?',[after,now(),a.id]);
  await tx.runAsync('INSERT INTO financial_movements(id,payment_method,direction,amount,document_id,document_number,party_id,party_name,type,transfer_id,note,delta,balance_before,balance_after,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id('fin'),a.id,args.direction,args.amount,args.documentId,args.documentNumber,args.partyId??null,args.partyName??null,args.type,args.transferId??null,args.note??null,delta,a.balance,after,args.occurredAt]);
}
async function insertLine(tx:Tx, documentId:string,line:{productId:string|null;description:string;quantity:number;unitPrice:number;lineTotal:number;costAtSale?:number|null;grossProfit?:number|null;balanceBefore?:number|null;balanceAfter?:number|null}) {
  await tx.runAsync('INSERT INTO document_lines(id,document_id,product_id,description,quantity,unit_price,line_total,cost_at_sale,gross_profit,balance_before,balance_after) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[id('line'),documentId,line.productId,line.description,line.quantity,line.unitPrice,line.lineTotal,line.costAtSale??null,line.grossProfit??null,line.balanceBefore??null,line.balanceAfter??null]);
}
function documentNumber(prefix:string, sequence?:number) { return sequence?`${prefix}-${sequence}-${Date.now()}`:`${prefix}-${Date.now()}-${Crypto.randomUUID().slice(0,6)}`; }

export interface ProductInput { name:string;barcode?:string;pieceCost?:number|null;piecePrice?:number|null;wholesalePrice?:number|null;expiryDate?:string|null;note?:string|null;openingStock?:number;openingWarehouseId?:string; }
export async function createProduct(db:SQLiteDatabase,input:ProductInput) {
  if(!input.name.trim()) throw new AccountingError('اسم المنتج مطلوب');
  if((input.note?.length??0)>1000) throw new AccountingError('ملاحظة المنتج طويلة جدًا');
  return transactionResult(db,async tx=>{
    const barcode=input.barcode?.trim()??'';
    if(barcode && await tx.getFirstAsync('SELECT id FROM products WHERE barcode=?',[barcode])) throw new AccountingError('هذا الباركود مستخدم لمنتج آخر','duplicate_barcode');
    const sequence=await nextCounter(tx,'product'); const productId=id('product'); const stamp=now(); const opening=assertQuantity(input.openingStock??0,'opening stock',true);
    const pieceCost=input.pieceCost==null?null:assertMoney(input.pieceCost,'purchase price',true); const piecePrice=input.piecePrice==null?null:assertMoney(input.piecePrice,'sale price',true); const wholesalePrice=input.wholesalePrice==null?null:assertMoney(input.wholesalePrice,'wholesale price',true);
    if(opening>0 && (!pieceCost || !input.openingWarehouseId)) throw new AccountingError('سعر الشراء والمخزن مطلوبان عند إدخال رصيد بداية');
    await tx.runAsync('INSERT INTO products(id,sku,name,barcode,piece_cost,last_purchase_cost,last_purchase_at,piece_price,wholesale_price,expiry_date,note,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[productId,String(sequence),input.name.trim(),barcode,pieceCost,opening>0?pieceCost:null,opening>0?stamp:null,piecePrice,wholesalePrice,input.expiryDate||null,input.note?.trim()||null,stamp,stamp]);
    if(opening>0 && input.openingWarehouseId){const wh=await activeWarehouse(tx,input.openingWarehouseId);const docId=id('adjustment'),number=documentNumber('OPEN');await tx.runAsync("INSERT INTO documents(id,number,kind,status,warehouse_id,warehouse_name,title,total,due_total,paid_total,cash_amount,occurred_at,revision) VALUES(?,?,'adjustment','posted',?,?,?,0,0,0,0,?,0)",[docId,number,wh.id,wh.name,'رصيد بداية',stamp]);const p=await product(tx,productId);const moved=await changeStock(tx,{product:p,warehouse:wh,delta:opening,documentId:docId,documentNumber:number,movementType:'opening',occurredAt:stamp});await insertLine(tx,docId,{productId,description:input.name.trim(),quantity:opening,unitPrice:pieceCost??0,lineTotal:0,balanceBefore:moved.before,balanceAfter:moved.after});}
    return productId;
  });
}

export async function archiveProduct(db:SQLiteDatabase,productId:string,restore=false){return transactionResult(db,async tx=>{await product(tx,productId,false);const result=await tx.runAsync('UPDATE products SET is_archived=?,archived_at=?,updated_at=? WHERE id=?',[restore?0:1,restore?null:now(),now(),productId]);if(!result.changes)throw new AccountingError('المنتج غير موجود');return productId;});}
export async function createParty(db:SQLiteDatabase,input:{name:string;phone?:string;partyType:PartyType}){if(!input.name.trim())throw new AccountingError('اسم الحساب مطلوب');return transactionResult(db,async tx=>{const phone=input.phone?.trim()??'';if(phone){const existing=await tx.getFirstAsync<{id:string}>('SELECT id FROM parties WHERE phone=? AND party_type=?',[phone,input.partyType]);if(existing)return existing.id;}const partyId=id('party'),stamp=now();await tx.runAsync('INSERT INTO parties(id,name,phone,party_type,receivable,payable,net,created_at,updated_at) VALUES(?,?,?,?,0,0,0,?,?)',[partyId,input.name.trim(),phone,input.partyType,stamp,stamp]);return partyId;});}
export async function createWarehouse(db:SQLiteDatabase,name:string){if(!name.trim())throw new AccountingError('اسم المخزن مطلوب');return transactionResult(db,async tx=>{const warehouseId=id('warehouse'),stamp=now();await tx.runAsync('INSERT INTO warehouses(id,name,is_sales_default,created_at,updated_at) VALUES(?,?,0,?,?)',[warehouseId,name.trim(),stamp,stamp]);return warehouseId;});}
export async function setDefaultWarehouse(db:SQLiteDatabase,warehouseId:string){return transactionResult(db,async tx=>{await activeWarehouse(tx,warehouseId);await tx.runAsync('UPDATE warehouses SET is_sales_default=0,updated_at=?',[now()]);await tx.runAsync('UPDATE warehouses SET is_sales_default=1,updated_at=? WHERE id=?',[now(),warehouseId]);return warehouseId;});}

export interface InvoiceInput { warehouseId:string;partyId?:string|null;paymentMethod:string;cashAmount?:number;pricingMode?:PricingMode;lines:Array<{productId:string;quantity:number;unitPrice:number}>; }
async function postInvoice(db:SQLiteDatabase,kind:'sale'|'purchase',input:InvoiceInput){
  if(!input.lines.length)throw new AccountingError('يجب إضافة منتج واحد على الأقل'); const ids=new Set(input.lines.map(l=>l.productId));if(ids.size!==input.lines.length)throw new AccountingError('لا يمكن تكرار المنتج في الفاتورة');
  return transactionResult(db,async tx=>{
    const wh=await activeWarehouse(tx,input.warehouseId); const pty=input.partyId?await party(tx,input.partyId):null; if(pty&&pty.party_type!==(kind==='sale'?'customer':'supplier'))throw new AccountingError(kind==='sale'?'يجب اختيار عميل صالح':'يجب اختيار مورد صالح');
    const method=input.paymentMethod; const cash=method==='note'?0:assertMoney(input.cashAmount??0,'cash amount',true); if(method!=='note')await account(tx,method);
    const prepared=[] as Array<{p:ProductDb;quantity:number;unitPrice:number;lineTotal:number;cost:number|null;grossProfit:number|null}>;
    for(const line of input.lines){const p=await product(tx,line.productId);const quantity=assertQuantity(line.quantity);const unitPrice=assertMoney(line.unitPrice,kind==='sale'?'sale price':'purchase price');if(kind==='sale'&&isProductExpired({expiryDate:p.expiry_date},today()))throw new AccountingError(`انتهت صلاحية ${p.name} ولا يمكن بيعه`,'expired');const lineTotal=roundLineTotal(quantity,unitPrice);const cost=kind==='sale'?p.last_purchase_cost??p.piece_cost:null;prepared.push({p,quantity,unitPrice,lineTotal,cost,grossProfit:cost==null?null:lineTotal-Math.round(quantity*cost)});}
    const total=prepared.reduce((s,l)=>s+l.lineTotal,0);const paid=Math.min(total,cash);const due=Math.max(total-cash,0);const partyDelta=kind==='sale'?total-cash:-total+cash;if(partyDelta!==0&&!pty)throw new AccountingError(kind==='sale'?'اختر عميلاً عند وجود مبلغ مستحق':'اختر موردًا عند وجود مبلغ مستحق');
    const sequence=await nextCounter(tx,kind);const stamp=now();const businessDate=today();const daily=kind==='sale'?Number((await tx.getFirstAsync<{value:number|null}>("SELECT MAX(daily_sequence) value FROM documents WHERE kind='sale' AND business_date=?",[businessDate]))?.value??0)+1:null;const docId=id(kind);const number=documentNumber(kind==='sale'?'SAL':'PUR',sequence);const snapshot=pty&&partyDelta!==0?await applyPartyDelta(tx,pty.id,partyDelta):null;
    await tx.runAsync('INSERT INTO documents(id,number,sequence,kind,status,party_id,party_name,warehouse_id,warehouse_name,payment_method,total,due_total,paid_total,cash_amount,party_balance_before,party_balance_delta,party_balance_after,business_date,daily_sequence,pricing_mode,occurred_at,revision) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)',[docId,number,sequence,kind,'posted',pty?.id??null,pty?.name??(kind==='sale'?'بيع مباشر':'شراء مباشر'),wh.id,wh.name,method,total,due,paid,cash,snapshot?.before??null,snapshot?.delta??null,snapshot?.after??null,businessDate,daily,input.pricingMode??(kind==='sale'?'retail':null),stamp]);
    for(const line of prepared){await changeStock(tx,{product:line.p,warehouse:wh,delta:kind==='sale'?-line.quantity:line.quantity,documentId:docId,documentNumber:number,movementType:kind,occurredAt:stamp});await insertLine(tx,docId,{productId:line.p.id,description:line.p.name,quantity:line.quantity,unitPrice:line.unitPrice,lineTotal:line.lineTotal,costAtSale:line.cost,grossProfit:line.grossProfit});if(kind==='purchase')await tx.runAsync('UPDATE products SET last_purchase_cost=?,last_purchase_at=?,updated_at=? WHERE id=?',[line.unitPrice,stamp,stamp,line.p.id]);}
    if(cash>0)await financialMovement(tx,{accountId:method,direction:kind==='sale'?'in':'out',amount:cash,documentId:docId,documentNumber:number,partyId:pty?.id,partyName:pty?.name,type:kind,occurredAt:stamp});
    await audit(tx,`${kind}.post`,docId);return docId;
  });
}
export const postSale=(db:SQLiteDatabase,input:InvoiceInput)=>postInvoice(db,'sale',input);
export const postPurchase=(db:SQLiteDatabase,input:InvoiceInput)=>postInvoice(db,'purchase',input);

export async function transferStock(db:SQLiteDatabase,input:{fromWarehouseId:string;toWarehouseId:string;lines:Array<{productId:string;quantity:number}>}){if(input.fromWarehouseId===input.toWarehouseId)throw new AccountingError('اختر مخزنين مختلفين');return transactionResult(db,async tx=>{const from=await activeWarehouse(tx,input.fromWarehouseId),to=await activeWarehouse(tx,input.toWarehouseId);const stamp=now(),docId=id('transfer'),number=documentNumber('TRF');await tx.runAsync("INSERT INTO documents(id,number,kind,status,warehouse_id,warehouse_name,destination_warehouse_id,destination_warehouse_name,total,due_total,paid_total,cash_amount,occurred_at,revision) VALUES(?,?,'transfer','posted',?,?,?,?,0,0,0,0,?,0)",[docId,number,from.id,from.name,to.id,to.name,stamp]);for(const line of input.lines){const p=await product(tx,line.productId),quantity=assertQuantity(line.quantity);await changeStock(tx,{product:p,warehouse:from,delta:-quantity,documentId:docId,documentNumber:number,movementType:'transfer-out',occurredAt:stamp});await changeStock(tx,{product:p,warehouse:to,delta:quantity,documentId:docId,documentNumber:number,movementType:'transfer-in',occurredAt:stamp});await insertLine(tx,docId,{productId:p.id,description:p.name,quantity,unitPrice:0,lineTotal:0});}await audit(tx,'transfer.post',docId);return docId;});}

export async function adjustStock(db:SQLiteDatabase,input:{warehouseId:string;reason:string;lines:Array<{productId:string;actualQuantity:number;purchaseCost?:number|null}>}){if(!input.reason.trim())throw new AccountingError('سبب التصحيح مطلوب');return transactionResult(db,async tx=>{const wh=await activeWarehouse(tx,input.warehouseId),stamp=now(),docId=id('adjustment'),number=documentNumber('ADJ');const changes=[] as Array<{p:ProductDb;before:number;after:number;purchaseCost:number|null}>;for(const line of input.lines){const p=await product(tx,line.productId),before=await stock(tx,p.id,wh.id),after=assertQuantity(line.actualQuantity,'actual quantity',true),purchaseCost=line.purchaseCost==null?null:assertMoney(line.purchaseCost,'purchase cost');if(after>before&&p.last_purchase_cost==null&&p.piece_cost==null&&purchaseCost==null)throw new AccountingError(`تكلفة الشراء مطلوبة لإضافة مخزون ${p.name}`);if(after!==before)changes.push({p,before,after,purchaseCost});}if(!changes.length)throw new AccountingError('لا يوجد تغيير في المخزون لاعتماده');await tx.runAsync("INSERT INTO documents(id,number,kind,status,warehouse_id,warehouse_name,title,total,due_total,paid_total,cash_amount,occurred_at,revision) VALUES(?,?,'adjustment','posted',?,?,?,0,0,0,0,?,0)",[docId,number,wh.id,wh.name,input.reason.trim(),stamp]);for(const change of changes){if(change.after>change.before&&change.p.last_purchase_cost==null&&change.purchaseCost!=null)await tx.runAsync('UPDATE products SET last_purchase_cost=?,last_purchase_at=?,updated_at=? WHERE id=?',[change.purchaseCost,stamp,stamp,change.p.id]);const moved=await changeStock(tx,{product:change.p,warehouse:wh,delta:change.after-change.before,documentId:docId,documentNumber:number,movementType:'adjustment',occurredAt:stamp});await insertLine(tx,docId,{productId:change.p.id,description:`${change.p.name} — ${input.reason.trim()}`,quantity:change.after-change.before,unitPrice:change.p.last_purchase_cost??change.purchaseCost??change.p.piece_cost??0,lineTotal:0,balanceBefore:moved.before,balanceAfter:moved.after});}await audit(tx,'adjustment.post',docId);return docId;});}

export async function postPartyCash(db:SQLiteDatabase,input:{partyId:string;direction:'receive'|'pay';amount:number;paymentMethod:string;note?:string}){return transactionResult(db,async tx=>{const p=await party(tx,input.partyId);const amount=assertMoney(input.amount);await account(tx,input.paymentMethod);const snapshot=await applyPartyDelta(tx,p.id,partyCashDelta(input.direction,amount));const stamp=now(),docId=id('payment'),number=documentNumber('PAY');await tx.runAsync("INSERT INTO documents(id,number,kind,status,party_id,party_name,payment_method,title,total,due_total,paid_total,cash_amount,party_cash_direction,party_balance_before,party_balance_delta,party_balance_after,occurred_at,revision) VALUES(?,?,'payment','posted',?,?,?,?,?,0,?,?,?, ?,?,?,?,0)",[docId,number,p.id,p.name,input.paymentMethod,input.direction==='receive'?'استلام من الطرف':'دفع للطرف',amount,amount,amount,input.direction,snapshot.before,snapshot.delta,snapshot.after,stamp]);await financialMovement(tx,{accountId:input.paymentMethod,direction:input.direction==='receive'?'in':'out',amount,documentId:docId,documentNumber:number,partyId:p.id,partyName:p.name,type:input.direction==='receive'?'party-receipt':'party-payment',occurredAt:stamp,note:input.note});await audit(tx,'party-cash.post',docId);return docId;});}

export async function postExpense(db:SQLiteDatabase,input:{title:string;amount:number;paymentMethod:string;businessDate:string}){if(!input.title.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(input.businessDate))throw new AccountingError('العنوان والتاريخ مطلوبان');return transactionResult(db,async tx=>{const amount=assertMoney(input.amount);await account(tx,input.paymentMethod);const sequence=await nextCounter(tx,'expense'),docId=id('expense'),number=documentNumber('EXP',sequence),occurredAt=new Date(`${input.businessDate}T12:00:00.000Z`).toISOString();await tx.runAsync("INSERT INTO documents(id,number,sequence,kind,status,payment_method,title,total,due_total,paid_total,cash_amount,occurred_at,revision) VALUES(?,?,?,'expense','posted',?,?,?,0,?,?,?,0)",[docId,number,sequence,input.paymentMethod,input.title.trim(),amount,amount,amount,occurredAt]);await insertLine(tx,docId,{productId:null,description:input.title.trim(),quantity:1,unitPrice:amount,lineTotal:amount});await financialMovement(tx,{accountId:input.paymentMethod,direction:'out',amount,documentId:docId,documentNumber:number,type:'expense',occurredAt});await audit(tx,'expense.post',docId);return docId;});}

export async function createPaymentAccount(db:SQLiteDatabase,input:{name:string;openingBalance?:number}){if(!input.name.trim())throw new AccountingError('اسم وسيلة الدفع مطلوب');return transactionResult(db,async tx=>{const opening=Number(input.openingBalance??0);if(!Number.isSafeInteger(opening))throw new AccountingError('رصيد البداية غير صالح');const accountId=id('account'),stamp=now(),code=id('custom');await tx.runAsync('INSERT INTO payment_accounts(id,code,name,color,icon,is_active,is_archived,opening_balance,balance,created_at,updated_at) VALUES(?,?,?,\'#1677c8\',\'wallet\',1,0,?,0,?,?)',[accountId,code,input.name.trim(),opening,stamp,stamp]);if(opening!==0){const docId=id('opening'),number=documentNumber('OPEN');await financialMovement(tx,{accountId,direction:opening>=0?'in':'out',amount:Math.abs(opening),documentId:docId,documentNumber:number,type:'opening-balance',occurredAt:stamp});}return accountId;});}

export async function transferAccount(db:SQLiteDatabase,input:{fromAccountId:string;toAccountId:string;amount:number;note?:string}){if(input.fromAccountId===input.toAccountId)throw new AccountingError('اختر حسابين مختلفين');return transactionResult(db,async tx=>{await account(tx,input.fromAccountId);await account(tx,input.toAccountId);const amount=assertMoney(input.amount),transferId=id('transfer'),number=documentNumber('BTR'),stamp=now();await financialMovement(tx,{accountId:input.fromAccountId,direction:'out',amount,documentId:transferId,documentNumber:number,type:'transfer-out',occurredAt:stamp,transferId,note:input.note});await financialMovement(tx,{accountId:input.toAccountId,direction:'in',amount,documentId:transferId,documentNumber:number,type:'transfer-in',occurredAt:stamp,transferId,note:input.note});await tx.runAsync('INSERT INTO account_transfers(id,number,from_account_id,to_account_id,amount,note,occurred_at) VALUES(?,?,?,?,?,?,?)',[transferId,number,input.fromAccountId,input.toAccountId,amount,input.note?.trim()||null,stamp]);await audit(tx,'account-transfer.post',transferId);return transferId;});}

export async function adjustAccount(db:SQLiteDatabase,input:{accountId:string;direction:'deposit'|'withdrawal';amount:number;note?:string}){return transactionResult(db,async tx=>{const amount=assertMoney(input.amount),stamp=now(),docId=id('account-adjustment'),number=documentNumber(input.direction==='deposit'?'DEP':'WDR');await financialMovement(tx,{accountId:input.accountId,direction:input.direction==='deposit'?'in':'out',amount,documentId:docId,documentNumber:number,type:input.direction==='deposit'?'manual-deposit':'manual-withdrawal',occurredAt:stamp,note:input.note});await audit(tx,'account-adjustment.post',docId);return docId;});}

export async function correctOpeningBalance(db:SQLiteDatabase,input:{accountId:string;newOpeningBalance:number;reason:string}){if(!input.reason.trim())throw new AccountingError('سبب التصحيح مطلوب');return transactionResult(db,async tx=>{const a=await account(tx,input.accountId,false);const next=input.newOpeningBalance;if(!Number.isSafeInteger(next))throw new AccountingError('رصيد البداية الصحيح غير صالح');const delta=next-a.opening_balance;if(delta===0)throw new AccountingError('رصيد البداية الجديد يطابق الرصيد الحالي');const after=a.balance+delta,stamp=now(),movementId=id('fin'),number=documentNumber('OPEN-COR');await tx.runAsync('UPDATE payment_accounts SET opening_balance=?,balance=?,updated_at=? WHERE id=?',[next,after,stamp,a.id]);await tx.runAsync("INSERT INTO financial_movements(id,payment_method,direction,amount,document_id,document_number,type,delta,balance_before,balance_after,opening_balance_before,opening_balance_after,reason,note,occurred_at) VALUES(?,?,?,?,?,?,'opening-balance-correction',?,?,?,?,?,?,?,?)",[movementId,a.id,delta>=0?'in':'out',Math.abs(delta),movementId,number,delta,a.balance,after,a.opening_balance,next,input.reason.trim(),input.reason.trim(),stamp]);await audit(tx,'account-opening-balance-correction.post',movementId);return movementId;});}

async function audit(tx:Tx,action:string,entityId:string){await tx.runAsync('INSERT INTO audit_events(id,action,entity_id,status,created_at) VALUES(?,?,?,?,?)',[id('audit'),action,entityId,'committed',now()]);}
async function transactionResult<T>(db:SQLiteDatabase,work:(tx:Tx)=>Promise<T>):Promise<T>{let output:T|undefined;await db.withExclusiveTransactionAsync(async tx=>{output=await work(tx)});if(output===undefined)throw new Error('Transaction produced no result');return output;}
