import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { SQLiteDatabase } from 'expo-sqlite';
import type { DocumentRecord, Locale } from '@/domain/types';
import { getInvoiceBranding } from './branding-service';

const escapeHtml=(value:unknown)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const money=(value:number,locale:Locale)=>new Intl.NumberFormat(locale==='ar'?'ar-MR-u-nu-latn':'fr-MR-u-nu-latn',{maximumFractionDigits:0}).format(value);
const qty=(value:number,locale:Locale)=>new Intl.NumberFormat(locale==='ar'?'ar-MR-u-nu-latn':'fr-MR-u-nu-latn',{maximumFractionDigits:3}).format(value);
const kindLabel=(kind:DocumentRecord['kind'],locale:Locale)=>({sale:locale==='ar'?'فاتورة بيع':'Facture de vente',purchase:locale==='ar'?'فاتورة شراء':"Facture d'achat",expense:locale==='ar'?'مصروف':'Dépense',transfer:locale==='ar'?'تحويل مخزون':'Transfert de stock',adjustment:locale==='ar'?'تصحيح مخزون':'Correction de stock',payment:locale==='ar'?'دفع / تحصيل':'Paiement',offset:locale==='ar'?'مقاصة':'Compensation',settlement:locale==='ar'?'تسوية':'Règlement',return:locale==='ar'?'حركة تاريخية':'Mouvement historique'}[kind]);
const fontFamily=(font:string)=>font==='times-new-roman'?"'Times New Roman',serif":font==='arial'?'Arial,sans-serif':font==='segoe-ui'?"'Segoe UI',sans-serif":'Tahoma,Arial,sans-serif';

export async function invoiceHtml(db:SQLiteDatabase,document:DocumentRecord,locale:Locale){
  const brand=await getInvoiceBranding(db),rtl=locale==='ar',labels=rtl?{number:'رقم المستند',date:'التاريخ',party:'الطرف',warehouse:'المخزن',item:'البيان',quantity:'الكمية',price:'السعر',total:'الإجمالي',paid:'المدفوع',due:'المتبقي',status:'الحالة',posted:'معتمد',voided:'ملغى',registration:'السجل',tax:'الرقم الضريبي'}:{number:'N°',date:'Date',party:'Client / Fournisseur',warehouse:'Dépôt',item:'Désignation',quantity:'Qté',price:'Prix',total:'Total',paid:'Payé',due:'Reste',status:'Statut',posted:'Validé',voided:'Annulé',registration:'Registre',tax:'N° fiscal'};
  const details=[brand.storePhone,brand.storeAddress,brand.registrationNumber?`${labels.registration}: ${brand.registrationNumber}`:'',brand.taxNumber?`${labels.tax}: ${brand.taxNumber}`:''].filter(Boolean).map(value=>`<div>${escapeHtml(value)}</div>`).join('');
  const rows=document.lines.map(line=>`<tr><td>${escapeHtml(line.description)}</td><td>${qty(line.quantity,locale)}</td><td>${money(line.unitPrice,locale)}</td><td>${money(line.lineTotal,locale)} MRU</td></tr>`).join('');
  const meta=[`${labels.number}: ${document.number}`,`${labels.date}: ${new Intl.DateTimeFormat(rtl?'ar-MR-u-nu-latn':'fr-MR-u-nu-latn',{dateStyle:'medium'}).format(new Date(document.occurredAt))}`,document.partyName?`${labels.party}: ${document.partyName}`:'',document.warehouseName?`${labels.warehouse}: ${document.warehouseName}`:'',`${labels.status}: ${document.status==='voided'?labels.voided:labels.posted}`].filter(Boolean).map(value=>`<div>${escapeHtml(value)}</div>`).join('');
  return `<!doctype html><html dir="${rtl?'rtl':'ltr'}"><head><meta charset="utf-8"><style>@page{margin:28px}*{box-sizing:border-box}body{font-family:Arial,Tahoma,sans-serif;color:#171717;font-size:12px;line-height:1.55;margin:0}.brand{text-align:center;border-bottom:2px solid #222;padding-bottom:14px;margin-bottom:16px}.brand h1{font-family:${fontFamily(brand.nameFont)};font-size:${brand.nameFontSize}px;font-weight:${brand.nameFontWeight};margin:0 0 6px}.brand .details{color:#555}.doc-title{text-align:center;font-size:18px;font-weight:800;margin:8px 0 14px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:5px 18px;background:#f7f7f7;border:1px solid #ddd;border-radius:8px;padding:10px;margin-bottom:14px}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #ddd;padding:8px 6px;text-align:${rtl?'right':'left'};vertical-align:top}th{background:#f0f0f0;font-weight:800}.totals{margin-top:14px;margin-${rtl?'right':'left'}:auto;width:270px;border:1px solid #ddd;border-radius:8px;overflow:hidden}.totals div{display:flex;justify-content:space-between;padding:7px 10px;border-bottom:1px solid #eee}.totals div:last-child{border-bottom:0;font-weight:800;font-size:14px}.void{color:#a11;font-weight:800}.footer{text-align:center;margin-top:22px;padding-top:12px;border-top:1px solid #ddd;color:#555;white-space:pre-wrap}</style></head><body><section class="brand"><h1>${escapeHtml(brand.storeName)}</h1><div class="details">${details}</div></section><div class="doc-title ${document.status==='voided'?'void':''}">${escapeHtml(kindLabel(document.kind,locale))}${document.status==='voided'?` — ${labels.voided}`:''}</div><section class="meta">${meta}</section><table><thead><tr><th>${labels.item}</th><th>${labels.quantity}</th><th>${labels.price}</th><th>${labels.total}</th></tr></thead><tbody>${rows||`<tr><td colspan="4">—</td></tr>`}</tbody></table><section class="totals"><div><span>${labels.paid}</span><strong>${money(document.paidTotal,locale)} MRU</strong></div><div><span>${labels.due}</span><strong>${money(document.dueTotal,locale)} MRU</strong></div><div><span>${labels.total}</span><strong>${money(document.total,locale)} MRU</strong></div></section>${brand.footerNote?`<div class="footer">${escapeHtml(brand.footerNote)}</div>`:''}</body></html>`;
}

export async function shareDocumentPdf(db:SQLiteDatabase,document:DocumentRecord,locale:Locale){
  const html=await invoiceHtml(db,document,locale),result=await Print.printToFileAsync({html});
  if(!(await Sharing.isAvailableAsync()))throw new Error(locale==='ar'?'المشاركة غير متاحة على هذا الجهاز.':'Le partage n’est pas disponible sur cet appareil.');
  await Sharing.shareAsync(result.uri,{mimeType:'application/pdf',dialogTitle:locale==='ar'?`مشاركة ${document.number}`:`Partager ${document.number}`,UTI:'com.adobe.pdf'});
  return result.uri;
}
