import type { SQLiteDatabase } from 'expo-sqlite';
import { assertMoney } from '@/domain/accounting';
import { AccountingError } from './accounting-service';

export interface ProductEditInput {name:string;barcode?:string;pieceCost?:number|null;piecePrice?:number|null;wholesalePrice?:number|null;expiryDate?:string|null;note?:string|null}
export async function updateProduct(db:SQLiteDatabase,productId:string,input:ProductEditInput){
  if(!input.name.trim())throw new AccountingError('اسم المنتج مطلوب');if((input.note?.length??0)>1000)throw new AccountingError('ملاحظة المنتج طويلة جدًا');
  const barcode=input.barcode?.trim()??'';if(barcode){const duplicate=await db.getFirstAsync<{id:string}>('SELECT id FROM products WHERE barcode=? AND id<>?',[barcode,productId]);if(duplicate)throw new AccountingError('هذا الباركود مستخدم لمنتج آخر','duplicate_barcode')}
  const existing=await db.getFirstAsync<{id:string}>('SELECT id FROM products WHERE id=?',[productId]);if(!existing)throw new AccountingError('المنتج غير موجود');
  const money=(value:number|null|undefined,label:string)=>value==null?null:assertMoney(value,label,true);
  await db.runAsync('UPDATE products SET name=?,barcode=?,piece_cost=?,piece_price=?,wholesale_price=?,expiry_date=?,note=?,updated_at=? WHERE id=?',[input.name.trim(),barcode,money(input.pieceCost,'purchase price'),money(input.piecePrice,'sale price'),money(input.wholesalePrice,'wholesale price'),input.expiryDate||null,input.note?.trim()||null,new Date().toISOString(),productId]);return productId;
}
export async function updateParty(db:SQLiteDatabase,partyId:string,input:{name:string;phone?:string}){const name=input.name.trim(),phone=input.phone?.trim()??'';if(!name)throw new AccountingError('اسم الحساب مطلوب');const party=await db.getFirstAsync<{id:string;party_type:'customer'|'supplier'}>('SELECT id,party_type FROM parties WHERE id=?',[partyId]);if(!party)throw new AccountingError('الحساب غير موجود');if(phone){const duplicate=await db.getFirstAsync<{id:string}>('SELECT id FROM parties WHERE phone=? AND party_type=? AND id<>?',[phone,party.party_type,partyId]);if(duplicate)throw new AccountingError('رقم الهاتف مستخدم لحساب آخر من نفس النوع','duplicate_phone')}await db.runAsync('UPDATE parties SET name=?,phone=?,updated_at=? WHERE id=?',[name,phone,new Date().toISOString(),partyId]);return partyId}
export async function renameWarehouse(db:SQLiteDatabase,warehouseId:string,name:string){if(!name.trim())throw new AccountingError('اسم المخزن مطلوب');const result=await db.runAsync('UPDATE warehouses SET name=?,updated_at=? WHERE id=? AND is_archived=0',[name.trim(),new Date().toISOString(),warehouseId]);if(!result.changes)throw new AccountingError('المخزن غير موجود');return warehouseId}
export async function archiveWarehouse(db:SQLiteDatabase,warehouseId:string){return runExclusive(db,async tx=>{const wh=await tx.getFirstAsync<{id:string;is_sales_default:number}>('SELECT id,is_sales_default FROM warehouses WHERE id=? AND is_archived=0',[warehouseId]);if(!wh)throw new AccountingError('المخزن غير موجود');if(wh.is_sales_default)throw new AccountingError('عيّن مخزنًا آخر للبيع قبل حذف هذا المخزن');const stocked=await tx.getFirstAsync<{found:number}>('SELECT 1 found FROM product_stocks WHERE warehouse_id=? AND quantity<>0 LIMIT 1',[warehouseId]);if(stocked)throw new AccountingError('لا يمكن حذف مخزن يحتوي على مخزون');const referenced=await tx.getFirstAsync<{found:number}>(`SELECT 1 found FROM documents WHERE warehouse_id=? OR destination_warehouse_id=? LIMIT 1`,[warehouseId,warehouseId]);if(referenced)await tx.runAsync('UPDATE warehouses SET is_archived=1,archived_at=?,updated_at=? WHERE id=?',[new Date().toISOString(),new Date().toISOString(),warehouseId]);else await tx.runAsync('DELETE FROM warehouses WHERE id=?',[warehouseId]);return warehouseId})}
export async function updatePaymentAccount(db:SQLiteDatabase,accountId:string,input:{name:string;color?:string}){if(!input.name.trim())throw new AccountingError('اسم وسيلة الدفع مطلوب');const color=input.color&&/^#[0-9a-f]{6}$/i.test(input.color)?input.color:'#1677c8';const result=await db.runAsync('UPDATE payment_accounts SET name=?,color=?,updated_at=? WHERE id=?',[input.name.trim(),color,new Date().toISOString(),accountId]);if(!result.changes)throw new AccountingError('وسيلة الدفع غير موجودة');return accountId}
export async function archivePaymentAccount(db:SQLiteDatabase,accountId:string){return runExclusive(db,async tx=>{const a=await tx.getFirstAsync<{id:string;code:string;balance:number}>('SELECT id,code,balance FROM payment_accounts WHERE id=?',[accountId]);if(!a)throw new AccountingError('وسيلة الدفع غير موجودة');if(a.code==='cash')throw new AccountingError('لا يمكن حذف وسيلة الدفع النقدية الأساسية');if(a.balance!==0)throw new AccountingError('صفّر أو سوِّ الرصيد أولًا');const referenced=await tx.getFirstAsync<{found:number}>(`SELECT 1 found FROM financial_movements WHERE payment_method=? UNION ALL SELECT 1 FROM documents WHERE payment_method=? UNION ALL SELECT 1 FROM account_transfers WHERE from_account_id=? OR to_account_id=? LIMIT 1`,[a.id,a.id,a.id,a.id]);if(referenced)await tx.runAsync('UPDATE payment_accounts SET is_active=0,is_archived=1,updated_at=? WHERE id=?',[new Date().toISOString(),a.id]);else await tx.runAsync('DELETE FROM payment_accounts WHERE id=?',[a.id]);return a.id})}
export async function restorePaymentAccount(db:SQLiteDatabase,accountId:string){const result=await db.runAsync('UPDATE payment_accounts SET is_active=1,is_archived=0,updated_at=? WHERE id=? AND is_archived=1',[new Date().toISOString(),accountId]);if(!result.changes)throw new AccountingError('وسيلة الدفع المؤرشفة غير موجودة');return accountId}
async function runExclusive<T>(db:SQLiteDatabase,work:(tx:SQLiteDatabase)=>Promise<T>):Promise<T>{let output:T|undefined;await db.withExclusiveTransactionAsync(async tx=>{output=await work(tx)});if(output===undefined)throw new Error('No transaction result');return output}
