import { useCallback, useState } from 'react';
import { Alert, FlatList, Modal, StyleSheet, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import type { DocumentRecord, PaymentAccount } from '@/domain/types';
import { listDocuments, listPaymentAccounts } from '@/db/queries';
import { postExpense } from '@/services/accounting-service';
import { AppText, Button, Card, Chip, EmptyState, Field, Money, Row, Screen, SectionTitle } from '@/components/ui';
import { useI18n } from '@/i18n/provider';
import { spacing } from '@/theme';
export function ExpensesScreen(){const db=useSQLiteContext(),{t,date}=useI18n();const [items,setItems]=useState<DocumentRecord[]>([]),[accounts,setAccounts]=useState<PaymentAccount[]>([]),[open,setOpen]=useState(false);const load=useCallback(async()=>{const [docs,a]=await Promise.all([listDocuments(db,{kind:'expense',limit:100}),listPaymentAccounts(db)]);setItems(docs);setAccounts(a)},[db]);useFocusEffect(useCallback(()=>{void load()},[load]));return <Screen><SectionTitle title={t('expenses')} action={<Button title={t('add')} onPress={()=>setOpen(true)}/>}/><FlatList data={items} keyExtractor={x=>x.id} ListEmptyComponent={<EmptyState title={t('noData')}/>} renderItem={({item})=><Row title={item.title??item.number} subtitle={`${date(item.occurredAt)} • ${item.number}`} trailing={<Money value={item.total} tone="negative"/>}/>}/><ExpenseModal visible={open} accounts={accounts} onClose={()=>setOpen(false)} onSave={async input=>{try{await postExpense(db,input);setOpen(false);await load();Alert.alert(t('success'))}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}}}/></Screen>}
function ExpenseModal({visible,accounts,onClose,onSave}:{visible:boolean;accounts:PaymentAccount[];onClose:()=>void;onSave:(input:{title:string;amount:number;paymentMethod:string;businessDate:string})=>Promise<void>}){const {t}=useI18n();const [title,setTitle]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(()=>new Date().toISOString().slice(0,10)),[method,setMethod]=useState(accounts.find(a=>a.code==='cash')?.id??accounts[0]?.id??'');return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><Screen scroll><SectionTitle title={t('createExpense')}/><Card><Field label={t('name')} value={title} onChangeText={setTitle}/><Field label={t('amount')} value={amount} keyboardType="number-pad" onChangeText={setAmount}/><Field label={t('date')} value={date} onChangeText={setDate}/><View style={styles.chips}>{accounts.map(a=><Chip key={a.id} label={a.name} active={method===a.id} onPress={()=>setMethod(a.id)}/>)}</View></Card><Button title={t('save')} onPress={()=>void onSave({title,amount:Number(amount),paymentMethod:method,businessDate:date})}/><Button title={t('cancel')} variant="ghost" onPress={onClose}/></Screen></Modal>}
const styles=StyleSheet.create({chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs}});
