import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { dashboardSummary, dashboardInsights } from '@/db/queries';
import { listDocumentHeaders } from '@/db/document-queries';
import type { DashboardSummary, DocumentRecord } from '@/domain/types';
import { Screen } from '@/components/ui';
import { StitchHeader, StitchIcon, StitchPanel, StitchSection, StitchText, stitch, type StitchIconName } from '@/components/stitch';
import { useI18n } from '@/i18n/provider';
import { useAuth } from '@/auth/provider';
const empty:DashboardSummary={todaySales:0,todayProfit:0,todayExpenses:0,receivable:0,payable:0,inventoryValue:0,lowStockCount:0};
export function HomeScreen(){
 const db=useSQLiteContext(),auth=useAuth(),{t,locale,isRTL,number,money}=useI18n(),ar=locale==='ar';
 const [summary,setSummary]=useState(empty),[recent,setRecent]=useState<DocumentRecord[]>([]),[count,setCount]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 const load=useCallback(async()=>{try{const [s,r,i]=await Promise.all([dashboardSummary(db),auth.has('records.view')?listDocumentHeaders(db,{limit:4}):Promise.resolve([]),dashboardInsights(db,1)]);setSummary(s);setRecent(r);setCount(i.trend.at(-1)?.saleCount??0);setError(false)}catch{setError(true)}finally{setLoading(false)}},[db,auth]);
 useFocusEffect(useCallback(()=>{void load()},[load]));
 const row={flexDirection:isRTL?'row-reverse' as const:'row' as const};
 const actions:{title:string;icon:StitchIconName;color:string;go:()=>void;allowed:boolean}[]=[
  {title:ar?'فاتورة بيع':t('newSale'),icon:'sale',color:stitch.blue,go:()=>router.push('/sales/pos'),allowed:auth.has('pos.create')},
  {title:ar?'فاتورة شراء':t('purchases'),icon:'purchase',color:stitch.amber,go:()=>router.push('/sales/purchases'),allowed:auth.has('purchases.create')||auth.has('purchases.view')},
  {title:ar?'سند قبض':'Encaissement',icon:'receive',color:stitch.green,go:()=>router.push('/parties/customers'),allowed:auth.has('customers.view')},
  {title:ar?'سند صرف':t('expenses'),icon:'spend',color:stitch.red,go:()=>router.push('/sales/expenses'),allowed:auth.has('expenses.view')},
 ];
 return <Screen padded={false}><StitchHeader module="DASHBOARD"/><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} tintColor={stitch.gold} onRefresh={()=>{setLoading(true);void load()}}/>}>
 {error?<Pressable onPress={()=>void load()}><StitchText color={stitch.red}>{t('homeLoadFailed')} · {t('tryAgain')}</StitchText></Pressable>:null}
 <StitchPanel style={s.hero}><View style={[s.heroHead,row]}><View style={[s.live,row]}><View style={s.liveDot}/><StitchText bold size={16}>{ar?'ملخص اليوم • مباشر':'Résumé du jour • en direct'}</StitchText></View><View style={s.shift}><StitchText size={10} color={stitch.lightGold}>{ar?'اليوم':'Aujourd’hui'}</StitchText></View></View>
 <View style={s.amountBlock}><StitchText size={12} color={stitch.muted}>{ar?'إجمالي مبيعات اليوم':t('todaySales')}</StitchText><View style={[s.amountRow,row]}>{loading?<ActivityIndicator color={stitch.green}/>:<StitchText bold size={32} color={stitch.green} style={s.numeric}>{number(summary.todaySales)}</StitchText>}<StitchText bold color={stitch.gold}>MRU</StitchText></View></View>
 <View style={[s.profitStrip,row]}><View style={[s.live,row]}><View style={s.profitIcon}><StitchIcon name="reports" color={stitch.green} size={18}/></View><View><StitchText size={11} color={stitch.muted}>{t('todayProfit')}</StitchText><StitchText bold size={14} color={stitch.green} style={s.numeric}>{money(summary.todayProfit)}</StitchText></View></View><View style={s.divider}/><View style={[s.live,row]}><StitchIcon name="receipt" size={18}/><StitchText bold size={12}>{number(count)} {ar?'عملية':'opérations'}</StitchText></View></View></StitchPanel>
 <View style={s.section}><StitchSection title={ar?'إجراءات سريعة':'Actions rapides'}/><View style={[s.actionGrid,row]}>{actions.filter(x=>x.allowed).map(x=><Pressable key={x.icon} accessibilityRole="button" onPress={x.go} style={({pressed})=>[s.quick,{backgroundColor:x.color},pressed&&s.pressed]}><View style={s.quickIcon}><StitchIcon name={x.icon} size={27} color="#FFFFFF"/></View><StitchText bold size={14} color="#FFFFFF">{x.title}</StitchText></Pressable>)}</View></View>
 <View style={[s.debts,row]}>{auth.has('customers.view')?<Debt title={ar?'ديون لنا (الزبائن)':t('receivable')} amount={summary.receivable} color={stitch.green} icon="people" hint={ar?'حسابات العملاء':'Comptes clients'} onPress={()=>router.push('/parties/customers')}/>:null}{auth.has('suppliers.view')?<Debt title={ar?'مستحقات (الموردون)':t('payable')} amount={summary.payable} color="#F59E0B" icon="receipt" hint={ar?'حسابات الموردين':'Comptes fournisseurs'} onPress={()=>router.push('/parties/suppliers')}/>:null}</View>
 {summary.lowStockCount>0&&auth.has('warehouses.inventory.view')?<Pressable style={s.warning} onPress={()=>router.push('/inventory/stock')}><StitchText color="#F59E0B">{t('lowStock')} · {number(summary.lowStockCount)}</StitchText></Pressable>:null}
 {auth.has('records.view')?<View style={s.section}><StitchSection title={ar?'أحدث المعاملات':'Dernières opérations'} action={ar?'عرض الكل':'Voir tout'} onPress={()=>router.push('/sales/records')}/>{recent.length?recent.map(doc=>{const outgoing=doc.kind==='purchase'||doc.kind==='expense'||doc.partyCashDirection==='pay';const color=outgoing?stitch.red:stitch.green;return <Pressable key={doc.id} accessibilityRole="button" style={({pressed})=>[s.transaction,row,pressed&&s.pressed]} onPress={()=>router.push({pathname:'/sales/records',params:{documentId:doc.id}})}><View style={[s.transactionIcon,{backgroundColor:(doc.kind==='sale'?stitch.blue:color)+'20'}]}><StitchIcon name={doc.kind==='sale'?'receipt':'wallet'} color={doc.kind==='sale'?stitch.blue:color} size={21}/></View><View style={s.txCopy}><StitchText bold size={14}>{doc.partyName??doc.title??t('records')}</StitchText><StitchText size={11} color={stitch.muted}>{doc.number} • {doc.kind==='sale'?t('sales'):doc.kind==='purchase'?t('purchases'):doc.kind==='expense'?t('expenses'):t('records')}</StitchText></View><View><StitchText bold size={13} color={color} style={s.numeric}>{money(doc.total)}</StitchText><StitchText size={10} color={stitch.muted}>{new Intl.DateTimeFormat(ar?'ar-MR':'fr-MR',{hour:'2-digit',minute:'2-digit'}).format(new Date(doc.occurredAt))}</StitchText></View></Pressable>}):<StitchPanel><StitchText size={12} color={stitch.muted}>{ar?'لم تسجل معاملات بعد. ابدأ بأول فاتورة أو سند.':'Aucune opération. Commencez par une facture ou un reçu.'}</StitchText></StitchPanel>}</View>:null}
 </ScrollView></Screen>;
}
function Debt({title,amount,color,icon,hint,onPress}:{title:string;amount:number;color:string;icon:StitchIconName;hint:string;onPress:()=>void}){const {isRTL,number}=useI18n(),row={flexDirection:isRTL?'row-reverse' as const:'row' as const};return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.debt,pressed&&s.pressed]}><View style={[s.debtHead,row]}><StitchText size={11} bold color={stitch.muted}>{title}</StitchText><View style={[s.debtDot,{backgroundColor:color}]}/></View><View style={[s.amountRow,row]}><StitchText size={21} bold style={s.numeric}>{number(amount)}</StitchText><StitchText size={11} color={stitch.gold}>MRU</StitchText></View><View style={[s.debtFoot,row]}><StitchIcon name={icon} color={color} size={14}/><StitchText size={10} color={stitch.muted}>{hint}</StitchText></View></Pressable>}
const s=StyleSheet.create({content:{padding:16,paddingTop:12,gap:20,paddingBottom:24},hero:{padding:20,borderColor:'rgba(212,175,55,.4)',borderRadius:16,gap:0},heroHead:{alignItems:'center',justifyContent:'space-between',paddingBottom:8,borderBottomWidth:1,borderBottomColor:'rgba(212,175,55,.2)'},live:{alignItems:'center',gap:7},liveDot:{width:8,height:8,borderRadius:4,backgroundColor:stitch.green},shift:{backgroundColor:'#332D1A',paddingHorizontal:10,paddingVertical:3,borderRadius:12},amountBlock:{paddingTop:16,paddingBottom:4,gap:2},amountRow:{alignItems:'baseline',gap:6},numeric:{fontVariant:['tabular-nums']},profitStrip:{marginTop:8,padding:10,borderWidth:1,borderColor:'rgba(212,175,55,.2)',borderRadius:12,backgroundColor:'#080C14',alignItems:'center',justifyContent:'space-between'},profitIcon:{width:28,height:28,borderRadius:7,alignItems:'center',justifyContent:'center',backgroundColor:'#0D2C26',borderWidth:1,borderColor:'#176149'},divider:{width:1,height:24,backgroundColor:'#283040'},section:{gap:8},actionGrid:{flexWrap:'wrap',gap:12},quick:{width:'48%',flexGrow:1,minHeight:112,borderWidth:1,borderColor:'rgba(212,175,55,.4)',borderRadius:12,alignItems:'center',justifyContent:'center',gap:10,paddingVertical:16},quickIcon:{width:48,height:48,borderRadius:12,backgroundColor:'rgba(255,255,255,.12)',borderWidth:1,borderColor:'rgba(255,255,255,.2)',alignItems:'center',justifyContent:'center'},debts:{gap:12},debt:{flex:1,minWidth:0,borderWidth:1,borderColor:stitch.border,borderRadius:12,backgroundColor:stitch.card,padding:12,gap:7},debtHead:{alignItems:'center',justifyContent:'space-between',gap:4},debtDot:{width:9,height:9,borderRadius:2},debtFoot:{borderTopWidth:1,borderTopColor:'rgba(212,175,55,.15)',paddingTop:6,alignItems:'center',gap:4},transaction:{backgroundColor:stitch.card,borderWidth:1,borderColor:stitch.border,borderRadius:12,padding:12,gap:10,alignItems:'center'},transactionIcon:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center'},txCopy:{flex:1,minWidth:0},warning:{backgroundColor:'#2D2516',padding:12,borderRadius:8},pressed:{opacity:.75,transform:[{translateY:1}]}});
