import { useState } from 'react';
import { KeyboardAvoidingView, Platform, StyleSheet, View } from 'react-native';
import { AppText, Badge, Button, Card, Field, Screen } from '@/components/ui';
import { useAuth } from '@/auth/provider';
import { useI18n } from '@/i18n/provider';
import { colors, radius, spacing } from '@/theme';

export function LoginScreen(){
  const {login}=useAuth(),{t,locale,isRTL}=useI18n(),ar=locale==='ar';
  const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async()=>{if(busy)return;setBusy(true);setError('');try{if(!await login(username.trim(),password))setError(ar?'اسم المستخدم أو كلمة المرور غير صحيحة':'Identifiant ou mot de passe incorrect.')}finally{setBusy(false)}};
  return <Screen padded={false}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.center}><View style={styles.hero}><View style={[styles.heroTop,{flexDirection:isRTL?'row-reverse':'row'}]}><Badge label={ar?'يعمل دون إنترنت':'Hors ligne'} tone="positive"/><Badge label={ar?'بيانات محلية':'Données locales'} tone="primary"/></View><View style={styles.brand}><AppText variant="display" style={styles.brandName}>{t('appName')}</AppText><AppText variant="subheading" style={styles.brandSubtitle}>{ar?'حسابات المحل، أسرع وأوضح من أول عملية.':'Les comptes du magasin, plus rapides et plus clairs dès la première opération.'}</AppText></View></View><Card style={styles.loginCard}><View style={styles.formTitle}><AppText variant="heading">{ar?'تسجيل الدخول':'Connexion'}</AppText><AppText variant="caption" muted>{ar?'أدخل حسابك المحلي للمتابعة.':'Utilisez votre compte local pour continuer.'}</AppText></View><Field label={ar?'اسم المستخدم':'Identifiant'} autoCapitalize="none" autoCorrect={false} value={username} onChangeText={setUsername} returnKeyType="next" autoFocus/><Field label={ar?'كلمة المرور':'Mot de passe'} secureTextEntry value={password} onChangeText={setPassword} onSubmitEditing={()=>void submit()} returnKeyType="done"/>{error?<Card tone="warning"><AppText variant="caption" style={styles.error}>{error}</AppText></Card>:null}<Button loading={busy} disabled={!username.trim()||!password} title={ar?'دخول إلى الكرنه':'Entrer dans Alkarna'} onPress={()=>void submit()}/></Card><AppText variant="caption" muted style={styles.footer}>{ar?'لا يحتاج تسجيل الدخول إلى اتصال بالإنترنت.':'La connexion ne nécessite pas Internet.'}</AppText></View></KeyboardAvoidingView></Screen>;
}

const styles=StyleSheet.create({flex:{flex:1},center:{flex:1,justifyContent:'center',padding:spacing.lg,gap:spacing.lg,backgroundColor:colors.background},hero:{borderRadius:radius.xl,backgroundColor:colors.primary,padding:spacing.lg,gap:spacing.xl},heroTop:{gap:spacing.xs,flexWrap:'wrap'},brand:{gap:spacing.sm},brandName:{color:colors.onPrimary},brandSubtitle:{color:'#DCEFE9',lineHeight:23},loginCard:{gap:spacing.md},formTitle:{gap:spacing.xxs},error:{color:colors.warning,fontWeight:'700'},footer:{textAlign:'center'}});
