import { View, StyleSheet } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/ui';
import { StitchHeader, StitchAction, StitchPanel, StitchSection, StitchIcon, StitchText, stitch } from '@/components/stitch';
import { useI18n } from '@/i18n/provider';
import { useAuth } from '@/auth/provider';
export function MoreHubScreen(){const {t,locale,isRTL}=useI18n(),auth=useAuth(),ar=locale==='ar';return <Screen scroll padded={false}><StitchHeader title={ar?'المزيد • الخدمات والإعدادات':t('more')} module=""/><View style={s.content}><StitchPanel><View style={[s.profile,{flexDirection:isRTL?'row-reverse':'row'}]}><View style={s.avatar}><StitchIcon name="shield" size={32}/></View><View style={s.copy}><StitchText bold size={20}>{auth.principal?.name??t('appName')}</StitchText><StitchText size={12} color={stitch.lightGold}>{ar?'الحساب المحلي • جلسة نشطة':'Compte local • session active'}</StitchText></View></View><View style={s.badges}><StitchText size={11} color={stitch.muted}>SQLite · {ar?'بيانات محلية':'Données locales'}</StitchText><StitchText size={11} color={stitch.green}>{ar?'يعمل دون اتصال':'Fonctionne hors ligne'}</StitchText></View></StitchPanel><StitchSection title={ar?'الخدمات والأدوات المركزية':'Services et outils'}/>
 {auth.has('banks.view')?<StitchAction title={ar?'الحسابات المالية والخزائن':t('accounts')} description={t('moreAccountsHint')} button={ar?'دخول الحسابات المالية':t('accounts')} icon="bank" onPress={()=>router.push('/more/accounts')}/>:null}
 {auth.has('reports.view')?<StitchAction title={ar?'التقارير الشاملة والأرباح':t('reports')} description={t('moreReportsHint')} button={ar?'استعراض التقارير':t('reports')} icon="reports" onPress={()=>router.push('/more/reports')}/>:null}
 {auth.has('settings.users.manage')?<StitchAction title={t('settingsUsers')} description={t('moreUsersHint')} button={ar?'إدارة فريق العمل':t('settingsUsers')} icon="shield" onPress={()=>router.push('/more/users')}/>:null}
 {auth.has('settings.view')?<><StitchAction title={ar?'هوية النشاط وتصميم الفواتير':t('brandingTitle')} description={ar?'اسم المحل، الهاتف، العنوان، وإعدادات الطباعة.':'Identité du commerce et impression des factures.'} button={ar?'تخصيص الهوية والطباعة':t('brandingTitle')} icon="warehouse" onPress={()=>router.push('/more/branding')}/><StitchAction title={ar?'الإعدادات والنسخ الاحتياطي':t('settings')} description={t('moreSettingsHint')} button={ar?'فتح أدوات النسخ واللغة':t('settings')} icon="backup" onPress={()=>router.push('/more/settings')}/></>:null}
 </View></Screen>}
const s=StyleSheet.create({content:{padding:16,gap:16},profile:{alignItems:'center',gap:14},avatar:{width:56,height:56,borderRadius:12,backgroundColor:'#2A2517',alignItems:'center',justifyContent:'center'},copy:{flex:1},badges:{flexDirection:'row',justifyContent:'space-between',paddingTop:12,borderTopWidth:1,borderTopColor:stitch.border}});
