import { useCallback, useState } from 'react';
import { Alert, FlatList, Modal, StyleSheet, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import type { DocumentRecord, Party, PaymentAccount } from '@/domain/types';
import { getParty, listDocuments, listPaymentAccounts } from '@/db/queries';
import { postPartyCash } from '@/services/accounting-service';
import { postOffset, postSettlement } from '@/services/party-ledger-service';
import { AppText, Button, Card, Chip, EmptyState, Field, Money, Row, Screen, SectionTitle } from '@/components/ui';
import { useI18n } from '@/i18n/provider';
import { useAuth } from '@/auth/provider';
import { spacing } from '@/theme';

type Action='receive'|'pay'|'settlement'|'offset'|null;

export function PartyDetailScreen(){
  const {id}=useLocalSearchParams<{id:string}>(),db=useSQLiteContext(),{t,date,isRTL}=useI18n(),auth=useAuth();
  const [party,setParty]=useState<Party|null>(null),[docs,setDocs]=useState<DocumentRecord[]>([]),[accounts,setAccounts]=useState<PaymentAccount[]>([]),[action,setAction]=useState<Action>(null);
  const load=useCallback(async()=>{if(!id)return;const [p,d,a]=await Promise.all([getParty(db,id),listDocuments(db,{partyId:id,limit:100}),listPaymentAccounts(db)]);setParty(p);setDocs(d);setAccounts(a)},[db,id]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  if(!party)return <Screen><Button title={t('cancel')} variant="ghost" onPress={()=>router.back()}/><EmptyState title={t('noData')}/></Screen>;
  const canView=auth.has(party.partyType==='customer'?'customers.view':'suppliers.view');
  const canMove=auth.has(party.partyType==='customer'?'customers.collect':'suppliers.pay');
  if(!canView)return <Screen><EmptyState title="ليس لديك صلاحية عرض هذا الحساب"/><Button title={t('cancel')} variant="ghost" onPress={()=>router.back()}/></Screen>;
  return <Screen><SectionTitle title={party.name} action={<Button title={t('cancel')} variant="ghost" onPress={()=>router.back()}/>}/><Card><AppText muted>{party.phone||'—'}</AppText><View style={[styles.balance,{flexDirection:isRTL?'row-reverse':'row'}]}><View><AppText variant="caption" muted>{party.net>0?t('receivable'):party.net<0?t('payable'):t('balance')}</AppText><Money value={Math.abs(party.net)} tone={party.net>0?'positive':party.net<0?'negative':'normal'}/><AppText variant="caption" muted>لنا: {party.receivable} • علينا: {party.payable}</AppText></View>{canMove?<View style={styles.actions}><Button title={t('receive')} onPress={()=>setAction('receive')}/><Button title={t('pay')} variant="secondary" onPress={()=>setAction('pay')}/><Button title="تسوية" variant="secondary" disabled={party.receivable<=0&&party.payable<=0} onPress={()=>setAction('settlement')}/>{party.receivable>0&&party.payable>0?<Button title="مقاصة" variant="secondary" onPress={()=>setAction('offset')}/>:null}</View>:null}</View></Card><SectionTitle title={t('records')}/><FlatList data={docs} keyExtractor={x=>x.id} ListEmptyComponent={<EmptyState title={t('noData')}/>} renderItem={({item})=><Row title={item.title??item.number} subtitle={`${date(item.occurredAt)} • ${item.number} • ${item.status==='voided'?t('voided'):t('posted')}`} trailing={<Money value={item.total}/>}/>}/>{action==='receive'||action==='pay'?<CashModal direction={action} accounts={accounts} onClose={()=>setAction(null)} onSave={async(amount,method,note)=>{try{await postPartyCash(db,{partyId:party.id,direction:action,amount,paymentMethod:method,note});setAction(null);await load();Alert.alert(t('success'))}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}}}/>:null}{action==='settlement'||action==='offset'?<LedgerModal mode={action} party={party} onClose={()=>setAction(null)} onSave={async(amount,note)=>{try{if(action==='offset')await postOffset(db,{partyId:party.id,amount,note});else await postSettlement(db,{partyId:party.id,side:party.receivable>0?'receivable':'payable',amount,note});setAction(null);await load();Alert.alert(t('success'))}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}}}/>:null}</Screen>;
}

function CashModal({direction,accounts,onClose,onSave}:{direction:'receive'|'pay';accounts:PaymentAccount[];onClose:()=>void;onSave:(amount:number,method:string,note:string)=>Promise<void>}){const {t}=useI18n();const [amount,setAmount]=useState(''),[method,setMethod]=useState(accounts.find(a=>a.code==='cash')?.id??accounts[0]?.id??''),[note,setNote]=useState('');return <Modal animationType="slide" onRequestClose={onClose}><Screen scroll><SectionTitle title={direction==='receive'?t('receive'):t('pay')}/><Card><Field label={t('amount')} value={amount} keyboardType="number-pad" onChangeText={setAmount}/><AppText variant="caption" muted>{t('paymentMethod')}</AppText><View style={styles.chips}>{accounts.map(a=><Chip key={a.id} label={a.name} active={method===a.id} onPress={()=>setMethod(a.id)}/>)}</View><Field label={t('note')} value={note} onChangeText={setNote}/></Card><Button title={t('confirm')} onPress={()=>void onSave(Number(amount),method,note)}/><Button title={t('cancel')} variant="ghost" onPress={onClose}/></Screen></Modal>}

function LedgerModal({mode,party,onClose,onSave}:{mode:'settlement'|'offset';party:Party;onClose:()=>void;onSave:(amount:number,note:string)=>Promise<void>}){const {t}=useI18n();const maximum=mode==='offset'?Math.min(party.receivable,party.payable):party.receivable>0?party.receivable:party.payable;const [amount,setAmount]=useState(String(maximum)),[note,setNote]=useState('');return <Modal animationType="slide" onRequestClose={onClose}><Screen scroll><SectionTitle title={mode==='offset'?'مقاصة':'تسوية محاسبية'}/><Card><AppText muted>{mode==='offset'?'تخفض المقاصة المبلغ المستحق لنا والمبلغ المستحق علينا بنفس القيمة دون حركة نقدية.':'التسوية تعدّل الرصيد المحاسبي للطرف دون إنشاء حركة نقدية.'}</AppText><AppText variant="caption" muted>الحد الأقصى: {maximum}</AppText><Field label={t('amount')} value={amount} keyboardType="number-pad" onChangeText={setAmount}/><Field label={t('note')} value={note} onChangeText={setNote}/></Card><Button title={t('confirm')} onPress={()=>void onSave(Number(amount),note)}/><Button title={t('cancel')} variant="ghost" onPress={onClose}/></Screen></Modal>}

const styles=StyleSheet.create({balance:{justifyContent:'space-between',alignItems:'center',gap:spacing.md},actions:{gap:spacing.xs,minWidth:110},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs}});
