import { useCallback, useState } from 'react';
import { Alert, FlatList, Modal, StyleSheet, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import type { DocumentRecord, Party, PaymentAccount } from '@/domain/types';
import { getParty, listDocuments, listPaymentAccounts } from '@/db/queries';
import { postPartyCash } from '@/services/accounting-service';
import { updateParty } from '@/services/management-service';
import { postOffset, postSettlement } from '@/services/party-ledger-service';
import { AppText, Button, Card, Chip, EmptyState, Field, Money, Row, Screen, SectionTitle } from '@/components/ui';
import { useI18n } from '@/i18n/provider';
import { useAuth } from '@/auth/provider';
import { spacing } from '@/theme';

type Action='receive'|'pay'|'settlement'|'offset'|'edit'|null;

export function PartyDetailScreen(){
  const {id}=useLocalSearchParams<{id:string}>(),db=useSQLiteContext(),{t,date,isRTL,locale}=useI18n(),auth=useAuth(),ar=locale==='ar';
  const [party,setParty]=useState<Party|null>(null),[docs,setDocs]=useState<DocumentRecord[]>([]),[accounts,setAccounts]=useState<PaymentAccount[]>([]),[action,setAction]=useState<Action>(null);
  const load=useCallback(async()=>{if(!id)return;const [p,d,a]=await Promise.all([getParty(db,id),listDocuments(db,{partyId:id,limit:100}),listPaymentAccounts(db)]);setParty(p);setDocs(d);setAccounts(a)},[db,id]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  if(!party)return <Screen><Button title={t('cancel')} variant="ghost" onPress={()=>router.back()}/><EmptyState title={t('noData')}/></Screen>;
  const canView=auth.has(party.partyType==='customer'?'customers.view':'suppliers.view'),canMove=auth.has(party.partyType==='customer'?'customers.collect':'suppliers.pay'),canEdit=auth.has(party.partyType==='customer'?'customers.edit':'suppliers.edit');
  if(!canView)return <Screen><EmptyState title={ar?'ليس لديك صلاحية عرض هذا الحساب':'Vous n’avez pas accès à ce compte.'}/><Button title={t('cancel')} variant="ghost" onPress={()=>router.back()}/></Screen>;
  return <Screen><SectionTitle title={party.name} action={<Button title={t('cancel')} variant="ghost" onPress={()=>router.back()}/>}/><Card><View style={[styles.profile,{flexDirection:isRTL?'row-reverse':'row'}]}><View style={styles.grow}><AppText muted>{party.phone||'—'}</AppText></View>{canEdit?<Button title={t('edit')} variant="secondary" onPress={()=>setAction('edit')}/>:null}</View><View style={[styles.balance,{flexDirection:isRTL?'row-reverse':'row'}]}><View><AppText variant="caption" muted>{party.net>0?t('receivable'):party.net<0?t('payable'):t('balance')}</AppText><Money value={Math.abs(party.net)} tone={party.net>0?'positive':party.net<0?'negative':'normal'}/><AppText variant="caption" muted>{ar?`لنا: ${party.receivable} • علينا: ${party.payable}`:`À recevoir : ${party.receivable} • À payer : ${party.payable}`}</AppText></View>{canMove?<View style={styles.actions}><Button title={t('receive')} onPress={()=>setAction('receive')}/><Button title={t('pay')} variant="secondary" onPress={()=>setAction('pay')}/><Button title={ar?'تسوية':'Règlement'} variant="secondary" disabled={party.receivable<=0&&party.payable<=0} onPress={()=>setAction('settlement')}/>{party.receivable>0&&party.payable>0?<Button title={ar?'مقاصة':'Compensation'} variant="secondary" onPress={()=>setAction('offset')}/>:null}</View>:null}</View></Card><SectionTitle title={t('records')}/><FlatList data={docs} keyExtractor={x=>x.id} ListEmptyComponent={<EmptyState title={t('noData')}/>} renderItem={({item})=><Row title={item.title??item.number} subtitle={`${date(item.occurredAt)} • ${item.number} • ${item.status==='voided'?t('voided'):t('posted')}`} trailing={<Money value={item.total}/>}/>}/>{action==='edit'?<PartyEditModal party={party} onClose={()=>setAction(null)} onSave={async(name,phone)=>{try{await updateParty(db,party.id,{name,phone});setAction(null);await load();Alert.alert(t('success'))}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}}}/>:null}{action==='receive'||action==='pay'?<CashModal direction={action} accounts={accounts} onClose={()=>setAction(null)} onSave={async(amount,method,note)=>{try{await postPartyCash(db,{partyId:party.id,direction:action,amount,paymentMethod:method,note});setAction(null);await load();Alert.alert(t('success'))}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}}}/>:null}{action==='settlement'||action==='offset'?<LedgerModal mode={action} party={party} onClose={()=>setAction(null)} onSave={async(amount,note)=>{try{if(action==='offset')await postOffset(db,{partyId:party.id,amount,note});else await postSettlement(db,{partyId:party.id,side:party.receivable>0?'receivable':'payable',amount,note});setAction(null);await load();Alert.alert(t('success'))}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}}}/>:null}</Screen>;
}

function PartyEditModal({party,onClose,onSave}:{party:Party;onClose:()=>void;onSave:(name:string,phone:string)=>Promise<void>}){const {t,locale}=useI18n(),ar=locale==='ar';const [name,setName]=useState(party.name),[phone,setPhone]=useState(party.phone);return <Modal animationType="slide" onRequestClose={onClose}><Screen scroll><SectionTitle title={ar?'تعديل بيانات الحساب':'Modifier le compte'}/><Card><Field label={t('name')} value={name} onChangeText={setName}/><Field label={t('phone')} keyboardType="phone-pad" value={phone} onChangeText={setPhone}/></Card><Button title={t('save')} onPress={()=>void onSave(name,phone)}/><Button title={t('cancel')} variant="ghost" onPress={onClose}/></Screen></Modal>}
function CashModal({direction,accounts,onClose,onSave}:{direction:'receive'|'pay';accounts:PaymentAccount[];onClose:()=>void;onSave:(amount:number,method:string,note:string)=>Promise<void>}){const {t}=useI18n();const [amount,setAmount]=useState(''),[method,setMethod]=useState(accounts.find(a=>a.code==='cash')?.id??accounts[0]?.id??''),[note,setNote]=useState('');return <Modal animationType="slide" onRequestClose={onClose}><Screen scroll><SectionTitle title={direction==='receive'?t('receive'):t('pay')}/><Card><Field label={t('amount')} value={amount} keyboardType="number-pad" onChangeText={setAmount}/><AppText variant="caption" muted>{t('paymentMethod')}</AppText><View style={styles.chips}>{accounts.map(a=><Chip key={a.id} label={a.name} active={method===a.id} onPress={()=>setMethod(a.id)}/>)}</View><Field label={t('note')} value={note} onChangeText={setNote}/></Card><Button title={t('confirm')} onPress={()=>void onSave(Number(amount),method,note)}/><Button title={t('cancel')} variant="ghost" onPress={onClose}/></Screen></Modal>}
function LedgerModal({mode,party,onClose,onSave}:{mode:'settlement'|'offset';party:Party;onClose:()=>void;onSave:(amount:number,note:string)=>Promise<void>}){const {t,locale}=useI18n(),ar=locale==='ar';const maximum=mode==='offset'?Math.min(party.receivable,party.payable):party.receivable>0?party.receivable:party.payable;const [amount,setAmount]=useState(String(maximum)),[note,setNote]=useState('');return <Modal animationType="slide" onRequestClose={onClose}><Screen scroll><SectionTitle title={mode==='offset'?(ar?'مقاصة':'Compensation'):(ar?'تسوية محاسبية':'Règlement comptable')}/><Card><AppText muted>{mode==='offset'?(ar?'تخفض المقاصة المبلغ المستحق لنا والمبلغ المستحق علينا بنفس القيمة دون حركة نقدية.':'La compensation réduit du même montant ce qui est à recevoir et à payer, sans mouvement de trésorerie.'):(ar?'التسوية تعدّل الرصيد المحاسبي للطرف دون إنشاء حركة نقدية.':'Le règlement ajuste le solde comptable sans créer de mouvement de trésorerie.')}</AppText><AppText variant="caption" muted>{ar?`الحد الأقصى: ${maximum}`:`Maximum : ${maximum}`}</AppText><Field label={t('amount')} value={amount} keyboardType="number-pad" onChangeText={setAmount}/><Field label={t('note')} value={note} onChangeText={setNote}/></Card><Button title={t('confirm')} onPress={()=>void onSave(Number(amount),note)}/><Button title={t('cancel')} variant="ghost" onPress={onClose}/></Screen></Modal>}
const styles=StyleSheet.create({profile:{alignItems:'center',gap:spacing.sm},grow:{flex:1},balance:{justifyContent:'space-between',alignItems:'center',gap:spacing.md},actions:{gap:spacing.xs,minWidth:110},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs}});
