import { useCallback, useState } from 'react';
import { Alert, FlatList, Modal, ScrollView, StyleSheet, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import type { Product, Warehouse } from '@/domain/types';
import { listProducts, listWarehouses } from '@/db/queries';
import { archiveProduct, createProduct } from '@/services/accounting-service';
import { updateProduct } from '@/services/management-service';
import { AppText, Button, Card, Chip, EmptyState, Field, Money, Row, Screen, SearchField, SectionTitle } from '@/components/ui';
import { useI18n } from '@/i18n/provider';
import { colors, spacing } from '@/theme';

const num=(value:string)=>value.trim()===''?null:Number(value);
export function ProductsScreen(){const db=useSQLiteContext(),{t,number}=useI18n();const [items,setItems]=useState<Product[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[search,setSearch]=useState(''),[editing,setEditing]=useState<Product|null|undefined>(undefined),[busy,setBusy]=useState(false);const load=useCallback(async()=>{setItems(await listProducts(db,search,undefined,false,100));setWarehouses(await listWarehouses(db))},[db,search]);useFocusEffect(useCallback(()=>{void load()},[load]));return <Screen><SectionTitle title={t('products')} action={<Button title={t('add')} onPress={()=>setEditing(null)}/>}/><SearchField value={search} onChangeText={setSearch}/><FlatList data={items} keyExtractor={item=>item.id} keyboardShouldPersistTaps="handled" ListEmptyComponent={<EmptyState title={search?t('noResults'):t('noData')}/>} renderItem={({item})=><Row title={item.name} subtitle={`${item.sku}${item.barcode?` • ${item.barcode}`:''} • ${number(Object.values(item.stocks??{}).reduce((a,b)=>a+b,0))}`} trailing={<Money value={item.piecePrice??0}/>} onPress={()=>setEditing(item)}/>}/>{editing!==undefined?<ProductEditor product={editing} warehouses={warehouses} busy={busy} onClose={()=>setEditing(undefined)} onSave={async input=>{setBusy(true);try{if(editing)await updateProduct(db,editing.id,input);else await createProduct(db,input);setEditing(undefined);await load()}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}finally{setBusy(false)}}} onArchive={editing?()=>Alert.alert(t('delete'),editing.name,[{text:t('cancel'),style:'cancel'},{text:t('confirm'),style:'destructive',onPress:()=>void (async()=>{try{await archiveProduct(db,editing.id);setEditing(undefined);await load()}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}})()}]):undefined}/>:null}</Screen>}

type Form={name:string;barcode:string;pieceCost:string;piecePrice:string;wholesalePrice:string;expiryDate:string;note:string;openingStock:string;openingWarehouseId:string};
function ProductEditor({product,warehouses,busy,onClose,onSave,onArchive}:{product:Product|null;warehouses:Warehouse[];busy:boolean;onClose:()=>void;onSave:(input:{name:string;barcode:string;pieceCost:number|null;piecePrice:number|null;wholesalePrice:number|null;expiryDate:string|null;note:string|null;openingStock?:number;openingWarehouseId?:string})=>Promise<void>;onArchive?:()=>void}){const {t,isRTL}=useI18n();const [form,setForm]=useState<Form>({name:product?.name??'',barcode:product?.barcode??'',pieceCost:String(product?.pieceCost??''),piecePrice:String(product?.piecePrice??''),wholesalePrice:String(product?.wholesalePrice??''),expiryDate:product?.expiryDate??'',note:product?.note??'',openingStock:'0',openingWarehouseId:warehouses.find(w=>w.isSalesDefault)?.id??warehouses[0]?.id??''});const set=(key:keyof Form)=>(value:string)=>setForm(current=>({...current,[key]:value}));return <Modal animationType="slide" onRequestClose={onClose}><Screen padded={false}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.modal}><SectionTitle title={product?product.name:t('createProduct')}/><Field label={t('name')} value={form.name} onChangeText={set('name')}/><Field label={t('barcode')} value={form.barcode} onChangeText={set('barcode')}/><View style={[styles.pair,{flexDirection:isRTL?'row-reverse':'row'}]}><Field label={t('purchasePrice')} value={form.pieceCost} onChangeText={set('pieceCost')} keyboardType="number-pad" style={styles.flex}/><Field label={t('salePrice')} value={form.piecePrice} onChangeText={set('piecePrice')} keyboardType="number-pad" style={styles.flex}/></View><Field label={t('wholesalePrice')} value={form.wholesalePrice} onChangeText={set('wholesalePrice')} keyboardType="number-pad"/><Field label={t('expiryDate')} value={form.expiryDate} onChangeText={set('expiryDate')} placeholder="YYYY-MM-DD"/><Field label={t('note')} value={form.note} onChangeText={set('note')} multiline/>{!product?<Card><AppText variant="subheading">{t('openingBalance')}</AppText><Field label={t('quantity')} value={form.openingStock} onChangeText={set('openingStock')} keyboardType="decimal-pad"/><View style={styles.chips}>{warehouses.map(w=><Chip key={w.id} label={w.name} active={form.openingWarehouseId===w.id} onPress={()=>set('openingWarehouseId')(w.id)}/>)}</View></Card>:null}<Button loading={busy} title={t('save')} onPress={()=>void onSave({name:form.name,barcode:form.barcode,pieceCost:num(form.pieceCost),piecePrice:num(form.piecePrice),wholesalePrice:num(form.wholesalePrice),expiryDate:form.expiryDate||null,note:form.note||null,...(!product?{openingStock:Number(form.openingStock||0),openingWarehouseId:form.openingWarehouseId}: {})})}/>{onArchive?<Button title={t('delete')} variant="danger" onPress={onArchive}/>:null}<Button title={t('cancel')} variant="ghost" onPress={onClose}/></ScrollView></Screen></Modal>}
const styles=StyleSheet.create({modal:{padding:spacing.md,gap:spacing.md,paddingBottom:spacing.xl,backgroundColor:colors.background},pair:{gap:spacing.sm},flex:{flex:1},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs}});
