import { useCallback, useMemo, useState } from 'react';
import { FlatList, Modal, ScrollView, StyleSheet, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import type { DocumentRecord } from '@/domain/types';
import { listDocuments } from '@/db/queries';
import { AppText, Button, Card, EmptyState, Money, Row, Screen, SearchField, SectionTitle } from '@/components/ui';
import { useI18n } from '@/i18n/provider';
import { colors, spacing } from '@/theme';
const labels:Record<DocumentRecord['kind'],string>={sale:'بيع',purchase:'شراء',return:'مرتجع',transfer:'تحويل',adjustment:'تصحيح',expense:'مصروف',payment:'دفع/تحصيل',offset:'مقاصة',settlement:'تسوية'};
export function RecordsScreen(){const db=useSQLiteContext(),{t,date}=useI18n();const [items,setItems]=useState<DocumentRecord[]>([]),[search,setSearch]=useState(''),[selected,setSelected]=useState<DocumentRecord|null>(null);const load=useCallback(async()=>setItems(await listDocuments(db,{search,limit:150})),[db,search]);useFocusEffect(useCallback(()=>{void load()},[load]));return <Screen><SectionTitle title={t('records')}/><SearchField value={search} onChangeText={setSearch}/><FlatList data={items} keyExtractor={x=>x.id} ListEmptyComponent={<EmptyState title={search?t('noResults'):t('noData')}/>} renderItem={({item})=><Row title={`${labels[item.kind]} • ${item.partyName??item.title??item.number}`} subtitle={`${date(item.occurredAt)} • ${item.number} • ${item.status==='voided'?t('voided'):t('posted')}`} trailing={<Money value={item.total}/>} onPress={()=>setSelected(item)}/>}/>{selected?<DocumentModal item={selected} onClose={()=>setSelected(null)}/>:null}</Screen>}
function DocumentModal({item,onClose}:{item:DocumentRecord;onClose:()=>void}){const {t,date,isRTL}=useI18n();const summary=useMemo(()=>[[t('total'),item.total],[t('paid'),item.paidTotal],[t('due'),item.dueTotal]] as const,[item,t]);return <Modal animationType="slide" onRequestClose={onClose}><Screen padded={false}><ScrollView contentContainerStyle={styles.modal}><SectionTitle title={item.number} action={<Button title={t('cancel')} variant="ghost" onPress={onClose}/>}/><Card><AppText variant="subheading">{item.partyName??item.title??labels[item.kind]}</AppText><AppText muted>{date(item.occurredAt)} • {item.warehouseName??''}</AppText>{summary.map(([label,value])=><View key={label} style={[styles.summary,{flexDirection:isRTL?'row-reverse':'row'}]}><AppText>{label}</AppText><Money value={value}/></View>)}</Card>{item.lines.map(line=><Card key={line.id}><AppText variant="subheading">{line.description}</AppText><View style={[styles.summary,{flexDirection:isRTL?'row-reverse':'row'}]}><AppText muted>{line.quantity} × {line.unitPrice}</AppText><Money value={line.lineTotal}/></View></Card>)}</ScrollView></Screen></Modal>}
const styles=StyleSheet.create({modal:{padding:spacing.md,gap:spacing.sm,paddingBottom:spacing.xxl,backgroundColor:colors.background},summary:{justifyContent:'space-between',alignItems:'center',gap:spacing.sm}});
