import { useCallback, useState } from 'react';
import { FlatList, ScrollView, StyleSheet, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { runReport, type ReportData, type ReportType } from '@/db/report-queries';
import { AppText, Card, Chip, Field, Money, Row, Screen, SectionTitle } from '@/components/ui';
import { useI18n } from '@/i18n/provider';
import { colors, spacing } from '@/theme';
const reportTypes:{id:ReportType;ar:string;fr:string}[]=[{id:'overview',ar:'نظرة عامة',fr:'Vue générale'},{id:'sales',ar:'المبيعات',fr:'Ventes'},{id:'purchases',ar:'المشتريات',fr:'Achats'},{id:'product-sales',ar:'مبيعات المنتجات',fr:'Ventes par produit'},{id:'stock',ar:'المخزون',fr:'Stock'},{id:'debts',ar:'الديون',fr:'Dettes'},{id:'party-ledger',ar:'كشف الأطراف',fr:'Comptes clients/fournisseurs'},{id:'financial',ar:'المالية',fr:'Finance'},{id:'expenses',ar:'المصاريف',fr:'Dépenses'}];
const metricLabels:Record<string,{ar:string;fr:string}>={sales:{ar:'المبيعات',fr:'Ventes'},purchases:{ar:'المشتريات',fr:'Achats'},expenses:{ar:'المصاريف',fr:'Dépenses'},profit:{ar:'الربح',fr:'Bénéfice'},total:{ar:'الإجمالي',fr:'Total'},count:{ar:'العدد',fr:'Nombre'},revenue:{ar:'الإيراد',fr:'Revenu'},inventory:{ar:'قيمة المخزون',fr:'Valeur du stock'},receivable:{ar:'لنا',fr:'À recevoir'},payable:{ar:'علينا',fr:'À payer'},incoming:{ar:'داخل',fr:'Entrées'},outgoing:{ar:'خارج',fr:'Sorties'},balance:{ar:'الرصيد',fr:'Solde'}};
export function ReportsScreen(){const db=useSQLiteContext(),{t,locale,isRTL,number}=useI18n();const [type,setType]=useState<ReportType>('overview'),[from,setFrom]=useState(()=>new Date(new Date().setDate(1)).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10)),[data,setData]=useState<ReportData>({metrics:[],rows:[]});const load=useCallback(async()=>setData(await runReport(db,type,from,to)),[db,type,from,to]);useFocusEffect(useCallback(()=>{void load()},[load]));const label=(key:string)=>metricLabels[key]?.[locale]??key;return <Screen padded={false}><FlatList data={data.rows} keyExtractor={x=>x.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><SectionTitle title={t('reports')}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{reportTypes.map(r=><Chip key={r.id} label={r[locale]} active={type===r.id} onPress={()=>setType(r.id)}/>)}</ScrollView><Card><View style={[styles.dates,{flexDirection:isRTL?'row-reverse':'row'}]}><View style={styles.flex}><Field label={t('from')} value={from} onChangeText={setFrom}/></View><View style={styles.flex}><Field label={t('to')} value={to} onChangeText={setTo}/></View></View></Card><View style={[styles.metrics,{flexDirection:isRTL?'row-reverse':'row'}]}>{data.metrics.map(m=><Card key={m.label} style={styles.metric}><AppText variant="caption" muted>{label(m.label)}</AppText>{m.label==='count'?<AppText variant="heading">{number(m.value)}</AppText>:<Money value={m.value} tone={m.label==='profit'||m.label==='incoming'||m.label==='receivable'?'positive':m.label==='expenses'||m.label==='outgoing'||m.label==='payable'?'negative':'normal'}/>}</Card>)}</View></View>} renderItem={({item})=><Row title={item.label} subtitle={item.secondary} trailing={<Money value={item.value} tone={item.extra!=null&&item.extra<0?'negative':'normal'}/>}/>} ListEmptyComponent={<Card><AppText muted>{t('noData')}</AppText></Card>}/></Screen>}
const styles=StyleSheet.create({content:{padding:spacing.md,gap:spacing.xs,paddingBottom:spacing.xxl,backgroundColor:colors.background},header:{gap:spacing.md},chips:{gap:spacing.xs},dates:{gap:spacing.sm},flex:{flex:1},metrics:{flexWrap:'wrap',gap:spacing.sm},metric:{minWidth:145,flexGrow:1}});
