import { useCallback, useState } from 'react';
import { Alert, ScrollView, StyleSheet, View } from 'react-native';
import { useFocusEffect, router } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import type { Product, Warehouse } from '@/domain/types';
import { listProducts, listWarehouses } from '@/db/queries';
import { transferStock } from '@/services/accounting-service';
import { ProductPicker } from '@/components/pickers';
import { AppText, Button, Card, Chip, EmptyState, Field, Screen, SectionTitle } from '@/components/ui';
import { useI18n } from '@/i18n/provider';
import { useAuth } from '@/auth/provider';
import { colors, spacing } from '@/theme';
type Line={productId:string;name:string;quantity:string};
export function TransferScreen(){const db=useSQLiteContext(),{t,isRTL}=useI18n(),auth=useAuth();const [products,setProducts]=useState<Product[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[lines,setLines]=useState<Line[]>([]),[picker,setPicker]=useState(false),[busy,setBusy]=useState(false);const allowed=auth.has('warehouses.transfer');const load=useCallback(async()=>{if(!allowed)return;const [p,w]=await Promise.all([listProducts(db,'',undefined,false,500),listWarehouses(db)]);setProducts(p);setWarehouses(w);setFrom(current=>current||w.find(x=>x.isSalesDefault)?.id||w[0]?.id||'');setTo(current=>current||w.find(x=>x.id!==(w.find(y=>y.isSalesDefault)?.id||w[0]?.id))?.id||'')},[allowed,db]);useFocusEffect(useCallback(()=>{void load()},[load]));if(!allowed)return <Screen><EmptyState title="ليس لديك صلاحية التحويل بين المخازن"/><Button title={t('cancel')} variant="ghost" onPress={()=>router.back()}/></Screen>;const submit=async()=>{setBusy(true);try{await transferStock(db,{fromWarehouseId:from,toWarehouseId:to,lines:lines.map(line=>({productId:line.productId,quantity:Number(line.quantity)}))});Alert.alert(t('success'));router.back()}catch(error){Alert.alert(t('error'),error instanceof Error?error.message:t('error'))}finally{setBusy(false)}};return <Screen padded={false}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><SectionTitle title={t('transfer')}/><Card><AppText variant="caption" muted>{t('from')}</AppText><View style={styles.chips}>{warehouses.map(w=><Chip key={w.id} label={w.name} active={from===w.id} onPress={()=>{setFrom(w.id);if(to===w.id)setTo('')}}/>)}</View><AppText variant="caption" muted>{t('to')}</AppText><View style={styles.chips}>{warehouses.filter(w=>w.id!==from).map(w=><Chip key={w.id} label={w.name} active={to===w.id} onPress={()=>setTo(w.id)}/>)}</View></Card><SectionTitle title={t('products')} action={<Button title={t('addLine')} onPress={()=>setPicker(true)}/>}/>{lines.map(line=><Card key={line.productId}><View style={[styles.line,{flexDirection:isRTL?'row-reverse':'row'}]}><AppText variant="subheading">{line.name}</AppText><Button title={t('remove')} variant="ghost" onPress={()=>setLines(x=>x.filter(y=>y.productId!==line.productId))}/></View><Field label={t('quantity')} keyboardType="decimal-pad" value={line.quantity} onChangeText={value=>setLines(current=>current.map(x=>x.productId===line.productId?{...x,quantity:value}:x))}/></Card>)}<Button loading={busy} disabled={!from||!to||!lines.length} title={t('confirm')} onPress={()=>void submit()}/><Button title={t('cancel')} variant="ghost" onPress={()=>router.back()}/></ScrollView><ProductPicker visible={picker} products={products} exclude={lines.map(l=>l.productId)} onClose={()=>setPicker(false)} onSelect={p=>setLines(current=>[...current,{productId:p.id,name:p.name,quantity:'1'}])}/></Screen>}
const styles=StyleSheet.create({content:{padding:spacing.md,gap:spacing.md,paddingBottom:spacing.xxl,backgroundColor:colors.background},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs},line:{justifyContent:'space-between',alignItems:'center'}});