import type { SQLiteDatabase } from 'expo-sqlite';
export type ReportType='overview'|'sales'|'purchases'|'product-sales'|'stock'|'debts'|'party-ledger'|'financial'|'expenses';
export type ReportMetric={label:string;value:number};
export type ReportRow={id:string;label:string;secondary:string;value:number;extra?:number};
export type ReportData={metrics:ReportMetric[];rows:ReportRow[]};
type Aggregate={total:number|null;count:number;profit?:number|null};
const isoEnd=(date:string)=>`${date}T23:59:59.999Z`,isoStart=(date:string)=>`${date}T00:00:00.000Z`;
export async function runReport(db:SQLiteDatabase,type:ReportType,from:string,to:string):Promise<ReportData>{
  const start=isoStart(from),end=isoEnd(to);
  if(type==='overview'){const sales=await db.getFirstAsync<Aggregate>("SELECT COALESCE(SUM(total),0) total,COUNT(*) count FROM documents WHERE kind='sale' AND status='posted' AND occurred_at BETWEEN ? AND ?",[start,end]);const purchases=await db.getFirstAsync<Aggregate>("SELECT COALESCE(SUM(total),0) total,COUNT(*) count FROM documents WHERE kind='purchase' AND status='posted' AND occurred_at BETWEEN ? AND ?",[start,end]);const expenses=await db.getFirstAsync<Aggregate>("SELECT COALESCE(SUM(total),0) total,COUNT(*) count FROM documents WHERE kind='expense' AND status='posted' AND occurred_at BETWEEN ? AND ?",[start,end]);const profit=await db.getFirstAsync<{total:number|null}>("SELECT COALESCE(SUM(l.gross_profit),0) total FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE d.kind='sale' AND d.status='posted' AND d.occurred_at BETWEEN ? AND ?",[start,end]);return{metrics:[{label:'sales',value:sales?.total??0},{label:'purchases',value:purchases?.total??0},{label:'expenses',value:expenses?.total??0},{label:'profit',value:profit?.total??0}],rows:[]}}
  if(type==='sales'||type==='purchases'||type==='expenses'){const kind=type==='sales'?'sale':type==='purchases'?'purchase':'expense';const rows=await db.getAllAsync<{day:string;total:number;count:number}>("SELECT substr(occurred_at,1,10) day,SUM(total) total,COUNT(*) count FROM documents WHERE kind=? AND status='posted' AND occurred_at BETWEEN ? AND ? GROUP BY day ORDER BY day DESC",[kind,start,end]);return{metrics:[{label:'total',value:rows.reduce((s,r)=>s+r.total,0)},{label:'count',value:rows.reduce((s,r)=>s+r.count,0)}],rows:rows.map(r=>({id:r.day,label:r.day,secondary:`${r.count}`,value:r.total}))}}
  if(type==='product-sales'){const rows=await db.getAllAsync<{product_id:string;description:string;quantity:number;revenue:number;profit:number|null}>("SELECT l.product_id,l.description,SUM(l.quantity) quantity,SUM(l.line_total) revenue,SUM(l.gross_profit) profit FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE d.kind='sale' AND d.status='posted' AND d.occurred_at BETWEEN ? AND ? GROUP BY l.product_id,l.description ORDER BY revenue DESC",[start,end]);return{metrics:[{label:'revenue',value:rows.reduce((s,r)=>s+r.revenue,0)},{label:'profit',value:rows.reduce((s,r)=>s+(r.profit??0),0)}],rows:rows.map(r=>({id:r.product_id??r.description,label:r.description,secondary:`qty ${r.quantity}`,value:r.revenue,extra:r.profit??0}))}}
  if(type==='stock'){const rows=await db.getAllAsync<{id:string;name:string;quantity:number;value:number}>("SELECT p.id,p.name,COALESCE(SUM(s.quantity),0) quantity,COALESCE(SUM(s.quantity*COALESCE(p.last_purchase_cost,p.piece_cost,0)),0) value FROM products p LEFT JOIN product_stocks s ON s.product_id=p.id WHERE p.is_archived=0 GROUP BY p.id,p.name ORDER BY p.name");return{metrics:[{label:'inventory',value:rows.reduce((s,r)=>s+r.value,0)}],rows:rows.map(r=>({id:r.id,label:r.name,secondary:`qty ${r.quantity}`,value:r.value,extra:r.quantity}))}}
  if(type==='debts'||type==='party-ledger'){const rows=await db.getAllAsync<{id:string;name:string;party_type:string;receivable:number;payable:number;net:number}>('SELECT id,name,party_type,receivable,payable,net FROM parties WHERE receivable<>0 OR payable<>0 ORDER BY ABS(net) DESC');return{metrics:[{label:'receivable',value:rows.reduce((s,r)=>s+r.receivable,0)},{label:'payable',value:rows.reduce((s,r)=>s+r.payable,0)}],rows:rows.map(r=>({id:r.id,label:r.name,secondary:r.party_type,value:Math.abs(r.net),extra:r.net}))}}
  if(type==='financial'){const accounts=await db.getAllAsync<{id:string;name:string;balance:number}>('SELECT id,name,balance FROM payment_accounts WHERE is_archived=0 ORDER BY name');const flow=await db.getFirstAsync<{incoming:number|null;outgoing:number|null}>("SELECT SUM(CASE WHEN direction='in' THEN amount ELSE 0 END) incoming,SUM(CASE WHEN direction='out' THEN amount ELSE 0 END) outgoing FROM financial_movements WHERE occurred_at BETWEEN ? AND ?",[start,end]);return{metrics:[{label:'incoming',value:flow?.incoming??0},{label:'outgoing',value:flow?.outgoing??0},{label:'balance',value:accounts.reduce((s,a)=>s+a.balance,0)}],rows:accounts.map(a=>({id:a.id,label:a.name,secondary:'balance',value:a.balance}))}}
  return {metrics:[],rows:[]};
}
