import type { SQLiteDatabase } from 'expo-sqlite';
import { validateRequiredDateRange } from '@/domain/date-range-validation';
export type ReportType='overview'|'sales'|'purchases'|'product-sales'|'stock'|'debts'|'party-ledger'|'financial'|'expenses';
export type ReportMetric={label:string;value:number};
export type ReportRow={id:string;label:string;secondary:string;value:number;extra?:number;format?:'money'|'number';sourceDocumentId?:string};
export type ReportData={metrics:ReportMetric[];rows:ReportRow[]};
export type ReportFilters={allTime?:boolean;productId?:string;categoryId?:string;partyId?:string;paymentAccountId?:string;movementType?:string;direction?:'in'|'out'|'';debtSide?:'receivable'|'payable'|'clear'|'';search?:string};
const isoEnd=(date:string)=>`${date}T23:59:59.999Z`,isoStart=(date:string)=>`${date}T00:00:00.000Z`;
const period=(column:string,from:string,to:string,allTime=false)=>allTime?{sql:'',args:[] as (string|number)[]}:{sql:` AND ${column} BETWEEN ? AND ?`,args:[isoStart(from),isoEnd(to)] as (string|number)[]};

export async function runReport(db:SQLiteDatabase,type:ReportType,from:string,to:string,filters:ReportFilters={}):Promise<ReportData>{
  if(type!=='debts'&&!filters.allTime){const issue=validateRequiredDateRange(from,to);if(issue)throw new Error(`invalid-report-range:${issue}`)}
  if(type==='debts')return debtsReport(db,filters);
  if(type==='party-ledger')return partyLedgerReport(db,from,to,filters);
  if(type==='stock')return stockReport(db,from,to,filters);
  if(type==='financial')return financialReport(db,from,to,filters);
  const range=period('d.occurred_at',from,to,filters.allTime);
  if(type==='overview'){
    const sum=async(kind:string)=>db.getFirstAsync<{total:number|null;count:number}>(`SELECT COALESCE(SUM(d.total),0) total,COUNT(*) count FROM documents d WHERE d.kind=? AND d.status='posted'${range.sql}`,[kind,...range.args]);
    const [sales,purchases,expenses]=await Promise.all([sum('sale'),sum('purchase'),sum('expense')]);
    const profit=await db.getFirstAsync<{total:number|null}>(`SELECT COALESCE(SUM(l.gross_profit),0) total FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE d.kind='sale' AND d.status='posted'${range.sql}`,range.args);
    const [inventory,debt,accounts]=await Promise.all([
      db.getFirstAsync<{value:number|null}>('SELECT COALESCE(SUM(s.quantity*COALESCE(p.last_purchase_cost,0)),0) value FROM product_stocks s JOIN products p ON p.id=s.product_id'),
      db.getFirstAsync<{receivable:number|null;payable:number|null}>('SELECT COALESCE(SUM(receivable),0) receivable,COALESCE(SUM(payable),0) payable FROM parties'),
      db.getFirstAsync<{balance:number|null}>('SELECT COALESCE(SUM(balance),0) balance FROM payment_accounts WHERE is_archived=0'),
    ]);
    const grossProfit=Number(profit?.total??0),expenseTotal=Number(expenses?.total??0);
    return{metrics:[
      {label:'sales',value:sales?.total??0},{label:'purchases',value:purchases?.total??0},{label:'expenses',value:expenseTotal},{label:'profit',value:grossProfit},{label:'netOperatingResult',value:grossProfit-expenseTotal},
      {label:'currentAccountsBalance',value:Number(accounts?.balance??0)},{label:'inventory',value:Number(inventory?.value??0)},{label:'receivable',value:Number(debt?.receivable??0)},{label:'payable',value:Number(debt?.payable??0)},
    ],rows:[]};
  }
  if(type==='sales'||type==='purchases')return tradeReport(db,type,from,to,filters);
  if(type==='expenses')return expenseReport(db,from,to,filters);
  if(type==='product-sales')return productSalesReport(db,from,to,filters);
  return{metrics:[],rows:[]};
}

async function tradeReport(db:SQLiteDatabase,type:'sales'|'purchases',from:string,to:string,filters:ReportFilters):Promise<ReportData>{
  const kind=type==='sales'?'sale':'purchase',range=period('d.occurred_at',from,to,filters.allTime),clauses=["d.kind=?","d.status='posted'"],args:(string|number)[]=[kind,...range.args];
  if(range.sql)clauses.push(range.sql.replace(/^ AND /,''));
  if(filters.paymentAccountId){clauses.push('d.payment_method=?');args.push(filters.paymentAccountId)}
  if(filters.productId){clauses.push('EXISTS(SELECT 1 FROM document_lines x WHERE x.document_id=d.id AND x.product_id=?)');args.push(filters.productId)}
  if(filters.categoryId){clauses.push('EXISTS(SELECT 1 FROM document_lines x JOIN products p ON p.id=x.product_id WHERE x.document_id=d.id AND p.category_id=?)');args.push(filters.categoryId)}
  const rows=await db.getAllAsync<{id:string;number:string;occurred_at:string;party_name:string|null;total:number;paid_total:number;due_total:number}>(`SELECT d.id,d.number,d.occurred_at,d.party_name,d.total,d.paid_total,d.due_total FROM documents d WHERE ${clauses.join(' AND ')} ORDER BY d.occurred_at DESC`,args);
  const filtered=Boolean(filters.productId||filters.categoryId);let total=0,profit=0,quantity=0;
  for(const row of rows){if(filtered){const clauses=['l.document_id=?'],lineArgs:(string|number)[]=[row.id];if(filters.productId){clauses.push('l.product_id=?');lineArgs.push(filters.productId)}if(filters.categoryId){clauses.push('p.category_id=?');lineArgs.push(filters.categoryId)}const line=await db.getFirstAsync<{value:number|null;quantity:number|null;profit:number|null}>(`SELECT SUM(l.line_total) value,SUM(l.quantity) quantity,SUM(l.gross_profit) profit FROM document_lines l LEFT JOIN products p ON p.id=l.product_id WHERE ${clauses.join(' AND ')}`,lineArgs);total+=Number(line?.value??0);quantity+=Number(line?.quantity??0);profit+=Number(line?.profit??0)}else{total+=row.total;const facts=await db.getFirstAsync<{quantity:number|null;profit:number|null}>('SELECT SUM(quantity) quantity,SUM(gross_profit) profit FROM document_lines WHERE document_id=?',[row.id]);quantity+=Number(facts?.quantity??0);profit+=Number(facts?.profit??0)}}
  const paid=rows.reduce((sum,row)=>sum+row.paid_total,0),due=rows.reduce((sum,row)=>sum+row.due_total,0);
  return{metrics:[{label:'total',value:total},{label:'count',value:rows.length},{label:'quantity',value:quantity},...(type==='sales'?[{label:'profit',value:profit}]:[]),{label:'paid',value:paid},{label:'due',value:due}],rows:await Promise.all(rows.map(async row=>{let value=row.total;if(filtered){const clauses=['l.document_id=?'],lineArgs:(string|number)[]=[row.id];if(filters.productId){clauses.push('l.product_id=?');lineArgs.push(filters.productId)}if(filters.categoryId){clauses.push('p.category_id=?');lineArgs.push(filters.categoryId)}const selected=await db.getFirstAsync<{value:number|null}>(`SELECT SUM(l.line_total) value FROM document_lines l LEFT JOIN products p ON p.id=l.product_id WHERE ${clauses.join(' AND ')}`,lineArgs);value=Number(selected?.value??0)}return{id:row.id,label:`${row.number} • ${row.party_name??(type==='sales'?'بيع مباشر':'شراء مباشر')}`,secondary:row.occurred_at.slice(0,10),value,sourceDocumentId:row.id}}))};
}

async function expenseReport(db:SQLiteDatabase,from:string,to:string,filters:ReportFilters):Promise<ReportData>{const range=period('d.occurred_at',from,to,filters.allTime),clauses=["d.kind='expense'","d.status='posted'"],args:(string|number)[]=[...range.args];if(range.sql)clauses.push(range.sql.replace(/^ AND /,''));if(filters.paymentAccountId){clauses.push('d.payment_method=?');args.push(filters.paymentAccountId)}const rows=await db.getAllAsync<{id:string;number:string;occurred_at:string;title:string|null;total:number;payment_method:string|null}>(`SELECT d.id,d.number,d.occurred_at,d.title,d.total,d.payment_method FROM documents d WHERE ${clauses.join(' AND ')} ORDER BY d.occurred_at DESC`,args);return{metrics:[{label:'total',value:rows.reduce((s,r)=>s+r.total,0)},{label:'count',value:rows.length}],rows:rows.map(r=>({id:r.id,label:r.title||r.number,secondary:`${r.occurred_at.slice(0,10)} • ${r.number}`,value:r.total,sourceDocumentId:r.id}))}}

async function productSalesReport(db:SQLiteDatabase,from:string,to:string,filters:ReportFilters):Promise<ReportData>{const range=period('d.occurred_at',from,to,filters.allTime),args:(string|number)[]=[...range.args],clauses=["d.kind='sale'","d.status='posted'"];if(range.sql)clauses.push(range.sql.replace(/^ AND /,''));if(filters.productId){clauses.push('l.product_id=?');args.push(filters.productId)}if(filters.categoryId){clauses.push('p.category_id=?');args.push(filters.categoryId)}const rows=await db.getAllAsync<{product_id:string;description:string;quantity:number;revenue:number;profit:number|null}>(`SELECT l.product_id,l.description,SUM(l.quantity) quantity,SUM(l.line_total) revenue,SUM(l.gross_profit) profit FROM document_lines l JOIN documents d ON d.id=l.document_id LEFT JOIN products p ON p.id=l.product_id WHERE ${clauses.join(' AND ')} GROUP BY l.product_id,l.description ORDER BY revenue DESC`,args);return{metrics:[{label:'revenue',value:rows.reduce((s,r)=>s+r.revenue,0)},{label:'quantity',value:rows.reduce((s,r)=>s+r.quantity,0)},{label:'profit',value:rows.reduce((s,r)=>s+(r.profit??0),0)}],rows:rows.map(r=>({id:r.product_id??r.description,label:r.description,secondary:`qty ${r.quantity}`,value:r.revenue,extra:r.profit??0}))}}

async function stockReport(db:SQLiteDatabase,from:string,to:string,filters:ReportFilters):Promise<ReportData>{const range=period('m.occurred_at',from,to,filters.allTime),clauses=['1=1'],args:(string|number)[]=[...range.args];if(range.sql)clauses.push(range.sql.replace(/^ AND /,''));if(filters.productId){clauses.push('m.product_id=?');args.push(filters.productId)}if(filters.categoryId){clauses.push('m.product_id IN (SELECT id FROM products WHERE category_id=?)');args.push(filters.categoryId)}if(filters.movementType){clauses.push('m.type=?');args.push(filters.movementType)}const rows=await db.getAllAsync<{id:string;document_id:string;occurred_at:string;product_name:string;warehouse_name:string;type:string;quantity_delta:number;balance_before:number;balance_after:number;document_number:string}>(`SELECT m.id,m.document_id,m.occurred_at,m.product_name,m.warehouse_name,m.type,m.quantity_delta,m.balance_before,m.balance_after,m.document_number FROM stock_movements m WHERE ${clauses.join(' AND ')} ORDER BY m.occurred_at DESC`,args);const incoming=rows.reduce((s,r)=>s+Math.max(0,r.quantity_delta),0),outgoing=rows.reduce((s,r)=>s+Math.abs(Math.min(0,r.quantity_delta)),0);return{metrics:[{label:'movements',value:rows.length},{label:'incoming',value:incoming},{label:'outgoing',value:outgoing},{label:'netChange',value:incoming-outgoing}],rows:rows.map(r=>({id:r.id,label:`${r.product_name} • ${r.warehouse_name}`,secondary:`${r.occurred_at.slice(0,10)} • ${r.type} • ${r.balance_before} → ${r.balance_after} • ${r.document_number}`,value:r.quantity_delta,format:'number',sourceDocumentId:r.document_id}))}}

async function debtsReport(db:SQLiteDatabase,filters:ReportFilters):Promise<ReportData>{const clauses=['is_archived=0'],args:(string|number)[]=[];if(filters.search){clauses.push('(name LIKE ? OR phone LIKE ?)');const q=`%${filters.search}%`;args.push(q,q)}if(filters.debtSide==='receivable')clauses.push('net>0');if(filters.debtSide==='payable')clauses.push('net<0');if(filters.debtSide==='clear')clauses.push('net=0');const rows=await db.getAllAsync<{id:string;name:string;phone:string;party_type:string;receivable:number;payable:number;net:number}>(`SELECT id,name,phone,party_type,receivable,payable,net FROM parties WHERE ${clauses.join(' AND ')} ORDER BY ABS(net) DESC,name`,args);const receivable=rows.reduce((s,r)=>s+Math.max(r.net,0),0),payable=rows.reduce((s,r)=>s+Math.max(-r.net,0),0);return{metrics:[{label:'receivable',value:receivable},{label:'payable',value:payable},{label:'net',value:receivable-payable},{label:'count',value:rows.length}],rows:rows.map(r=>({id:r.id,label:r.name,secondary:`${r.party_type} • ${r.phone||'—'}`,value:Math.abs(r.net),extra:r.net}))}}

async function partyLedgerReport(db:SQLiteDatabase,from:string,to:string,filters:ReportFilters):Promise<ReportData>{if(!filters.partyId)return{metrics:[],rows:[]};const party=await db.getFirstAsync<{id:string;name:string;receivable:number;payable:number;net:number}>('SELECT id,name,receivable,payable,net FROM parties WHERE id=?',[filters.partyId]);if(!party)return{metrics:[],rows:[]};const range=period('occurred_at',from,to,filters.allTime),args:(string|number)[]=[filters.partyId,...range.args],rows=await db.getAllAsync<{id:string;number:string;kind:string;title:string|null;total:number;cash_amount:number;party_balance_delta:number|null;payment_method:string|null;occurred_at:string}>(`SELECT id,number,kind,title,total,cash_amount,party_balance_delta,payment_method,occurred_at FROM documents WHERE party_id=? AND status='posted' AND kind IN ('sale','purchase','return','payment','offset','settlement')${range.sql} ORDER BY occurred_at DESC`,args);return{metrics:[{label:'receivable',value:party.receivable},{label:'payable',value:party.payable},{label:'net',value:party.net},{label:'count',value:rows.length}],rows:rows.map(r=>{let delta=r.party_balance_delta;if(delta==null){if(r.kind==='sale')delta=r.total;else if(r.kind==='purchase')delta=-r.total;else delta=0}return{id:r.id,label:`${r.number} • ${r.title??r.kind}`,secondary:`${r.occurred_at.slice(0,10)} • ${r.payment_method??'—'}`,value:Number(delta),format:'money',extra:Number(delta),sourceDocumentId:r.id}})}}

async function financialReport(db:SQLiteDatabase,from:string,to:string,filters:ReportFilters):Promise<ReportData>{const range=period('occurred_at',from,to,filters.allTime),clauses=["COALESCE(status,'posted')='posted'","COALESCE(is_reversal,0)=0"],args:(string|number)[]=[...range.args];if(range.sql)clauses.push(range.sql.replace(/^ AND /,''));if(filters.paymentAccountId){clauses.push('payment_method=?');args.push(filters.paymentAccountId)}if(filters.direction){clauses.push('direction=?');args.push(filters.direction)}if(filters.movementType){if(filters.movementType==='sale'||filters.movementType==='purchase'){clauses.push('(type=? OR type LIKE ?)');args.push(filters.movementType,`${filters.movementType}:%`)}else{clauses.push('type=?');args.push(filters.movementType)}}const rows=await db.getAllAsync<{id:string;document_id:string;payment_method:string;direction:'in'|'out';amount:number;document_number:string;party_name:string|null;type:string;occurred_at:string}>(`SELECT id,document_id,payment_method,direction,amount,document_number,party_name,type,occurred_at FROM financial_movements WHERE ${clauses.join(' AND ')} ORDER BY occurred_at DESC`,args);const incoming=rows.filter(r=>r.direction==='in').reduce((s,r)=>s+r.amount,0),outgoing=rows.filter(r=>r.direction==='out').reduce((s,r)=>s+r.amount,0),nonOperating=new Set(['transfer-in','transfer-out','opening-balance','opening-balance-correction','balance-correction']),operating=rows.filter(r=>!nonOperating.has(r.type)),businessIncoming=operating.filter(r=>r.direction==='in').reduce((s,r)=>s+r.amount,0),businessOutgoing=operating.filter(r=>r.direction==='out').reduce((s,r)=>s+r.amount,0);return{metrics:[{label:'incoming',value:incoming},{label:'outgoing',value:outgoing},{label:'net',value:incoming-outgoing},{label:'businessNet',value:businessIncoming-businessOutgoing},{label:'count',value:rows.length}],rows:rows.map(r=>({id:r.id,label:`${r.type} • ${r.party_name??r.payment_method}`,secondary:`${r.occurred_at.slice(0,10)} • ${r.document_number}`,value:r.amount,extra:r.direction==='in'?r.amount:-r.amount,sourceDocumentId:r.document_id}))}}
