import { useMemo, useState } from 'react';
import { FlatList, Modal, StyleSheet } from 'react-native';
import type { Party, Product } from '@/domain/types';
import { EmptyState, Row, Screen, SearchField, SectionTitle, Button } from './ui';
import { useI18n } from '@/i18n/provider';
import { spacing } from '@/theme';

export function ProductPicker({visible,products,onClose,onSelect,exclude=[]}:{visible:boolean;products:Product[];onClose:()=>void;onSelect:(product:Product)=>void;exclude?:string[]}){const {t}=useI18n();const [search,setSearch]=useState('');const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase();return products.filter(p=>!exclude.includes(p.id)&&(!q||`${p.name} ${p.sku} ${p.barcode}`.toLocaleLowerCase().includes(q)))},[products,exclude,search]);return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><Screen><SectionTitle title={t('products')} action={<Button title={t('cancel')} variant="ghost" onPress={onClose}/>}/><SearchField value={search} onChangeText={setSearch}/><FlatList data={filtered} keyExtractor={p=>p.id} keyboardShouldPersistTaps="handled" ListEmptyComponent={<EmptyState title={t('noResults')}/>} renderItem={({item})=><Row title={item.name} subtitle={`${item.sku}${item.barcode?` • ${item.barcode}`:''}`} onPress={()=>{onSelect(item);setSearch('');onClose()}}/>}/></Screen></Modal>}
export function PartyPicker({visible,parties,onClose,onSelect,directLabel}:{visible:boolean;parties:Party[];onClose:()=>void;onSelect:(party:Party|null)=>void;directLabel:string}){const {t}=useI18n();const [search,setSearch]=useState('');const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase();return parties.filter(p=>!q||`${p.name} ${p.phone}`.toLocaleLowerCase().includes(q))},[parties,search]);return <Modal visible={visible} animationType="slide" onRequestClose={onClose}><Screen><SectionTitle title={t('parties')} action={<Button title={t('cancel')} variant="ghost" onPress={onClose}/>}/><Button title={directLabel} variant="secondary" onPress={()=>{onSelect(null);onClose()}}/><SearchField value={search} onChangeText={setSearch}/><FlatList contentContainerStyle={styles.list} data={filtered} keyExtractor={p=>p.id} ListEmptyComponent={<EmptyState title={t('noResults')}/>} renderItem={({item})=><Row title={item.name} subtitle={item.phone||undefined} onPress={()=>{onSelect(item);setSearch('');onClose()}}/>}/></Screen></Modal>}
const styles=StyleSheet.create({list:{paddingBottom:spacing.xl}});
