import { forwardRef, type ReactNode } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, type TextInputProps, type TextStyle, View, type ViewStyle, type StyleProp } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing, touch, type as typography } from '@/theme';
import { useI18n } from '@/i18n/provider';

export function Screen({children,scroll=false,padded=true}:{children:ReactNode;scroll?:boolean;padded?:boolean}){const content=<View style={[styles.screenContent,padded&&styles.padded]}>{children}</View>;return <SafeAreaView edges={['top']} style={styles.safe}>{scroll?<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.scroll}>{content}</ScrollView>:content}</SafeAreaView>}
export function AppText({children,variant='body',muted=false,style}:{children:ReactNode;variant?:'title'|'heading'|'subheading'|'body'|'caption'|'amount';muted?:boolean;style?:StyleProp<TextStyle>}){const {isRTL}=useI18n();return <Text style={[styles.text,{fontSize:typography[variant],textAlign:isRTL?'right':'left'},muted&&styles.muted,style]}>{children}</Text>}
export function Card({children,style}:{children:ReactNode;style?:StyleProp<ViewStyle>}){return <View style={[styles.card,style]}>{children}</View>}
export function SectionTitle({title,action}:{title:string;action?:ReactNode}){const {isRTL}=useI18n();return <View style={[styles.sectionHead,{flexDirection:isRTL?'row-reverse':'row'}]}><AppText variant="heading">{title}</AppText>{action}</View>}
export function Button({title,onPress,variant='primary',disabled=false,loading=false}:{title:string;onPress:()=>void;variant?:'primary'|'secondary'|'danger'|'ghost';disabled?:boolean;loading?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled||loading} onPress={onPress} style={({pressed})=>[styles.button,variant==='primary'&&styles.buttonPrimary,variant==='secondary'&&styles.buttonSecondary,variant==='danger'&&styles.buttonDanger,variant==='ghost'&&styles.buttonGhost,(pressed||disabled)&&styles.buttonDim]}>{loading?<ActivityIndicator color={variant==='primary'?colors.onPrimary:colors.primary}/>:<Text style={[styles.buttonText,variant==='primary'&&styles.buttonTextPrimary,variant==='danger'&&styles.buttonTextPrimary]}>{title}</Text>}</Pressable>}
export const Field=forwardRef<TextInput,TextInputProps & {label:string;error?:string}>(({label,error,style,...props},ref)=>{const {isRTL}=useI18n();return <View style={styles.field}><AppText variant="caption" muted>{label}</AppText><TextInput ref={ref} placeholderTextColor={colors.textMuted} style={[styles.input,{textAlign:isRTL?'right':'left'},style]} {...props}/>{error?<Text style={styles.error}>{error}</Text>:null}</View>});Field.displayName='Field';
export function SearchField(props:Omit<TextInputProps,'style'>){const {t,isRTL}=useI18n();return <TextInput accessibilityLabel={t('search')} placeholder={t('search')} placeholderTextColor={colors.textMuted} style={[styles.search,{textAlign:isRTL?'right':'left'}]} {...props}/>}
export function EmptyState({title}:{title:string}){return <View style={styles.empty}><AppText muted>{title}</AppText></View>}
export function Money({value,tone='normal'}:{value:number;tone?:'normal'|'positive'|'negative'}){const {money}=useI18n();return <Text style={[styles.money,tone==='positive'&&styles.positive,tone==='negative'&&styles.negative]}>{money(value)}</Text>}
export function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityState={{selected:active}} onPress={onPress} style={({pressed})=>[styles.chip,active&&styles.chipActive,pressed&&styles.buttonDim]}><Text style={[styles.chipText,active&&styles.chipTextActive]}>{label}</Text></Pressable>}
export function Row({title,subtitle,trailing,onPress}:{title:string;subtitle?:string;trailing?:ReactNode;onPress?:()=>void}){const {isRTL}=useI18n();const body=<><View style={styles.rowBody}><AppText variant="subheading">{title}</AppText>{subtitle?<AppText variant="caption" muted>{subtitle}</AppText>:null}</View>{trailing}</>;return onPress?<Pressable onPress={onPress} style={({pressed})=>[styles.row,{flexDirection:isRTL?'row-reverse':'row'},pressed&&styles.rowPressed]}>{body}</Pressable>:<View style={[styles.row,{flexDirection:isRTL?'row-reverse':'row'}]}>{body}</View>}
export function Stat({label,value,tone='normal'}:{label:string;value:number;tone?:'normal'|'positive'|'negative'}){return <Card style={styles.stat}><AppText variant="caption" muted>{label}</AppText><Money value={value} tone={tone}/></Card>}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},screenContent:{flex:1,gap:spacing.md},padded:{paddingHorizontal:spacing.md},scroll:{flexGrow:1,paddingBottom:spacing.xl},text:{color:colors.text,fontWeight:'400'},muted:{color:colors.textMuted},card:{backgroundColor:colors.surface,borderRadius:radius.lg,borderCurve:'continuous',borderWidth:1,borderColor:colors.border,padding:spacing.md,gap:spacing.sm},sectionHead:{minHeight:touch.min,justifyContent:'space-between',alignItems:'center'},button:{minHeight:touch.min,borderRadius:radius.md,borderCurve:'continuous',paddingHorizontal:spacing.md,alignItems:'center',justifyContent:'center'},buttonPrimary:{backgroundColor:colors.primary},buttonSecondary:{backgroundColor:colors.primarySoft,borderWidth:1,borderColor:colors.primary},buttonDanger:{backgroundColor:colors.negative},buttonGhost:{backgroundColor:'transparent'},buttonDim:{opacity:.65},buttonText:{fontSize:typography.body,fontWeight:'700',color:colors.primary},buttonTextPrimary:{color:colors.onPrimary},field:{gap:spacing.xxs},input:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,borderCurve:'continuous',paddingHorizontal:spacing.sm,backgroundColor:colors.surface,color:colors.text,fontSize:typography.body},search:{minHeight:48,borderRadius:radius.full,paddingHorizontal:spacing.md,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,color:colors.text,fontSize:typography.body},error:{color:colors.negative,fontSize:typography.caption},empty:{minHeight:120,alignItems:'center',justifyContent:'center'},money:{fontSize:typography.amount,fontWeight:'800',color:colors.text,fontVariant:['tabular-nums']},positive:{color:colors.positive},negative:{color:colors.negative},chip:{minHeight:touch.min,paddingHorizontal:spacing.md,borderRadius:radius.full,backgroundColor:colors.surfaceMuted,alignItems:'center',justifyContent:'center'},chipActive:{backgroundColor:colors.primary},chipText:{color:colors.text,fontWeight:'600'},chipTextActive:{color:colors.onPrimary},row:{minHeight:60,alignItems:'center',gap:spacing.sm,paddingVertical:spacing.sm,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},rowBody:{flex:1,gap:spacing.xxs},rowPressed:{backgroundColor:colors.surfaceMuted},stat:{flex:1,minWidth:150}});
