export class StoreError extends Error {}
export class ShopDatabase {
  constructor(name='alkarna-site-v1'){this.name=name;this.db=null;this.revision=0}
  async open(){this.db=await new Promise((resolve,reject)=>{const r=indexedDB.open(this.name,1);r.onupgradeneeded=()=>{for(const name of ['snapshots','users','meta'])r.result.createObjectStore(name,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});this.db.onversionchange=()=>this.db.close();return this}
  async get(store,id){return new Promise((resolve,reject)=>{const r=this.db.transaction(store).objectStore(store).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async all(store){return new Promise((resolve,reject)=>{const r=this.db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async put(store,value){return new Promise((resolve,reject)=>{const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve(value);tx.onabort=tx.onerror=()=>reject(tx.error||new StoreError('تعذّر حفظ البيانات'))})}
  async load(){const row=await this.get('snapshots','shop');this.revision=row?.revision||0;return row?.state||null}
  async save(state,backup=null){validateState(state);const copy=structuredClone(state);return new Promise((resolve,reject)=>{const tx=this.db.transaction(['snapshots','meta'],'readwrite');const store=tx.objectStore('snapshots');let failure=null;const request=store.get('shop');request.onsuccess=()=>{if((request.result?.revision||0)!==this.revision){failure=new StoreError('تغيّرت البيانات من نافذة أخرى. أعد تحميل الموقع قبل متابعة التسجيل.');tx.abort();return}if(backup)store.put({id:'before-compact-product-names',state:structuredClone(backup),updatedAt:new Date().toISOString()});store.put({id:'shop',revision:this.revision+1,state:copy,updatedAt:new Date().toISOString()})};tx.oncomplete=()=>{this.revision++;resolve(this.revision)};tx.onabort=tx.onerror=()=>reject(failure||tx.error||new StoreError('لم يكتمل الحفظ؛ لم تُسجّل العملية'))})}
  async replace(state,users){validateState(state);for(const u of users)if(!u.id||!u.username||!['owner','manager','accountant','sales'].includes(u.role)||!/^([a-f0-9]{64})$/.test(u.password?.hash||'')||!/^([a-f0-9]{32})$/.test(u.password?.salt||''))throw new StoreError('حساب مستخدم غير صالح في النسخة');if(new Set(users.map(u=>u.username)).size!==users.length||new Set(users.map(u=>u.id)).size!==users.length)throw new StoreError('حسابات مكررة في النسخة');if(!users.some(u=>u.role==='owner'&&u.active!==false))throw new StoreError('النسخة تحتاج حساب مالك فعال');const old=await this.get('snapshots','shop');if((old?.revision||0)!==this.revision)throw new StoreError('تغيّرت البيانات من نافذة أخرى. أعد تحميل الموقع قبل الاستعادة.');return new Promise((resolve,reject)=>{const tx=this.db.transaction(['snapshots','users','meta'],'readwrite');tx.objectStore('snapshots').put({id:'safety-backup',state:old?.state,users:[] ,updatedAt:new Date().toISOString()});tx.objectStore('snapshots').put({id:'shop',state:structuredClone(state),revision:this.revision+1,updatedAt:new Date().toISOString()});tx.objectStore('users').clear();for(const user of users)tx.objectStore('users').put(user);tx.oncomplete=()=>{this.revision++;resolve()};tx.onabort=tx.onerror=()=>reject(tx.error||new StoreError('فشلت الاستعادة؛ بقيت البيانات السابقة'))})}
}
export function validateState(s){if(!s||typeof s!=='object'||!s.opening)throw new StoreError('بنية البيانات غير صالحة');for(const k of ['products','parties','accounts','records','warehouses'])if(!Array.isArray(s[k])||s[k].length>100000)throw new StoreError('بيانات '+k+' غير صالحة');for(const k of ['products','parties','accounts','records']){const ids=s[k].map(x=>x.id);if(ids.some(id=>!Number.isSafeInteger(id)||id<=0)||new Set(ids).size!==ids.length)throw new StoreError('معرّفات مكررة أو غير صالحة في '+k)}if(!s.warehouses.length||new Set(s.warehouses).size!==s.warehouses.length||s.warehouses.some(x=>typeof x!=='string'||!x.trim()))throw new StoreError('أسماء المخازن غير صالحة');const finite=(n)=>typeof n==='number'&&Number.isFinite(n)&&Math.abs(n)<=1e14;for(const p of s.products){if(!p.name?.trim()||![p.price,p.cost,p.wholesale??p.price].every(n=>finite(n)&&n>=0)||!p.stocks||Object.values(p.stocks).some(n=>!finite(n)||n<0)||Object.keys(p.stocks).some(w=>!s.warehouses.includes(w)))throw new StoreError('بيانات المنتج غير صالحة')}for(const a of s.accounts)if(!a.name?.trim()||!finite(a.balance)||a.balance<0)throw new StoreError('رصيد حساب غير صالح');for(const p of s.parties)if(!p.name?.trim()||!['customer','supplier'].includes(p.type)||!finite(p.balance))throw new StoreError('حساب طرف غير صالح');const kinds=['sale','purchase','expense','receive','pay','deposit','withdraw','transfer','stocktransfer','adjustment','offset'];for(const r of s.records){if(!kinds.includes(r.kind)||!finite(r.total)||r.total<0||!Array.isArray(r.lines)||!/^\d{4}-\d{2}-\d{2}$/.test(r.date||''))throw new StoreError('مستند غير صالح');if(!finite(r.paid??0)||!finite(r.due??0)||(r.paid??0)<0||(r.due??0)<0||r.to&&!s.accounts.some(a=>a.id===r.to)||r.otherParty&&!s.parties.some(p=>p.id===r.otherParty)||[r.warehouse,r.from,r.toWarehouse].filter(Boolean).some(w=>!s.warehouses.includes(w)))throw new StoreError('مبالغ أو مراجع المستند غير صالحة');if(r.party&&!s.parties.some(p=>p.id===r.party)||r.account&&!s.accounts.some(a=>a.id===r.account))throw new StoreError('المستند يشير إلى حساب غير موجود');for(const l of r.lines)if(!s.products.some(p=>p.id===l.product)||!finite(l.qty)||!finite(l.price)||l.qty<0||r.kind==='adjustment'&&!finite(l.delta))throw new StoreError('بند فاتورة غير صالح')}return true}
export async function passwordDigest(password,salt){const saltBytes=salt?Uint8Array.from(salt.match(/.{2}/g),x=>parseInt(x,16)):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:saltBytes,iterations:210000},key,256);const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');return {algorithm:'PBKDF2-SHA256',iterations:210000,salt:hex(saltBytes),hash:hex(bits)}}
export async function verifyPassword(password,stored){if(!stored?.salt||!stored?.hash)return false;const got=await passwordDigest(password,stored.salt);let diff=got.hash.length^stored.hash.length;for(let i=0;i<got.hash.length;i++)diff|=got.hash.charCodeAt(i)^stored.hash.charCodeAt(i);return diff===0}
