import {formatWorkbookFiles} from './xlsx-format.js';
const xml=v=>String(v??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const names={demoBatch:'دفعة البيانات التجريبية',id:'معرّف المستند',number:'رقم المستند',kind:'نوع الفاتورة',title:'الطرف / البيان',subtitle:'وصف الحركة',date:'التاريخ',time:'الوقت',total:'الإجمالي MRU',paid:'المدفوع MRU',due:'على الحساب MRU',profit:'الربح MRU',account:'معرّف وسيلة الدفع',party:'معرّف الطرف',warehouse:'المخزن',from:'من مخزن',toWarehouse:'إلى مخزن',to:'إلى حساب',note:'الملاحظة',voided:'ملغاة',revision:'عدد التعديلات',newQty:'الرصيد بعد التصحيح',otherParty:'الطرف المقابل',product:'معرّف المنتج',name:'المنتج',qty:'الكمية',price:'سعر الوحدة MRU',delta:'تغيير المخزون',costAtSale:'التكلفة وقت البيع MRU'};
const value=v=>v===undefined||v===null?'':typeof v==='object'?JSON.stringify(v):v;
export function recordExportData(state,records,labels){
 const enriched=records.map(r=>({...r,number:r.number||r.kind.toUpperCase()+'-'+r.id,kind:labels[r.kind]||r.kind,paymentAccount:state.accounts.find(a=>a.id===r.account)?.name||'',partyType:({customer:'عميل',supplier:'مورد'})[state.parties.find(p=>p.id===r.party)?.type]||'',destinationAccount:state.accounts.find(a=>a.id===r.to)?.name||'',otherPartyName:state.parties.find(p=>p.id===r.otherParty)?.name||''}));
 const columns=[...new Set(enriched.flatMap(Object.keys))].filter(k=>k!=='lines');
 const extra={paymentAccount:'وسيلة الدفع',partyType:'نوع الطرف',destinationAccount:'الحساب المستلم',otherPartyName:'اسم الطرف المقابل'};
 const lines=records.flatMap(r=>(r.lines||[]).map((l,i)=>({document:r.number||r.kind.toUpperCase()+'-'+r.id,line:i+1,...l,lineTotal:Number(l.qty)*Number(l.price)})));
 const lc=[...new Set(lines.flatMap(Object.keys))];
 return [{name:'المستندات',rows:[columns.map(k=>names[k]||extra[k]||k),...enriched.map(r=>columns.map(k=>value(r[k])))]},{name:'بنود المستندات',rows:[lc.map(k=>names[k]||({document:'رقم المستند',line:'رقم البند',lineTotal:'مجموع البند MRU'}[k])||k),...lines.map(l=>lc.map(k=>value(l[k])))]}];
}
function zip(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0;const crc=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0};for(const [name,text] of files){const n=enc.encode(name),b=enc.encode(text),c=crc(b),header=new Uint8Array(30+n.length),h=new DataView(header.buffer);h.setUint32(0,0x04034b50,true);h.setUint16(4,20,true);h.setUint32(14,c,true);h.setUint32(18,b.length,true);h.setUint32(22,b.length,true);h.setUint16(26,n.length,true);header.set(n,30);parts.push(header,b);const entry=new Uint8Array(46+n.length),e=new DataView(entry.buffer);e.setUint32(0,0x02014b50,true);e.setUint16(4,20,true);e.setUint16(6,20,true);e.setUint32(16,c,true);e.setUint32(20,b.length,true);e.setUint32(24,b.length,true);e.setUint16(28,n.length,true);e.setUint32(42,offset,true);entry.set(n,46);central.push(entry);offset+=header.length+b.length}const size=central.reduce((n,b)=>n+b.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,files.length,true);v.setUint16(10,files.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
export function recordWorkbook(sheets){const namespace='http://schemas.openxmlformats.org/spreadsheetml/2006/main',column=i=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s};const files=[['[Content_Types].xml',`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],['_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml',`<workbook xmlns="${namespace}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`],['xl/_rels/workbook.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`]];sheets.forEach((s,i)=>files.push([`xl/worksheets/sheet${i+1}.xml`,`<worksheet xmlns="${namespace}"><sheetViews><sheetView workbookViewId="0" rightToLeft="1"><pane ySplit="1" topLeftCell="A2" state="frozen"/></sheetView></sheetViews><sheetData>${s.rows.map((r,j)=>`<row r="${j+1}">${r.map((v,k)=>typeof v==='number'&&Number.isFinite(v)?`<c r="${column(k)}${j+1}"><v>${v}</v></c>`:`<c r="${column(k)}${j+1}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData></worksheet>`]));return zip(formatWorkbookFiles(files,sheets))}
export function recordPrintHtml(state,records,labels){return `<h1>${xml(state.branding)} — سجل الفواتير</h1><p>${records.length} مستندات · MRU</p>`+records.map(r=>{const data=recordExportData(state,[r],labels);return `<article class="export-document"><h2>${xml(labels[r.kind])} · ${xml(r.number||r.kind.toUpperCase()+'-'+r.id)}</h2><dl>${data[0].rows[0].map((h,i)=>`<div><dt>${xml(h)}</dt><dd>${xml(data[0].rows[1][i])}</dd></div>`).join('')}</dl>${data[1].rows.length>1?`<table><thead><tr>${data[1].rows[0].map(h=>`<th>${xml(h)}</th>`).join('')}</tr></thead><tbody>${data[1].rows.slice(1).map(row=>`<tr>${row.map(v=>`<td>${xml(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`:''}</article>`}).join('')}
