export function formatWorkbookFiles(files,sheets){
 const styles=`<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/><color rgb="FF25364A"/></font><font><b/><sz val="11"/><name val="Arial"/><color rgb="FFFFFFFF"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF294562"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF0F4F8"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"><color rgb="FFB7C4D2"/></left><right style="thin"><color rgb="FFB7C4D2"/></right><top style="thin"><color rgb="FFB7C4D2"/></top><bottom style="thin"><color rgb="FFB7C4D2"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="6">${[0,1,2,3,4,5].map(i=>`<xf numFmtId="${i>=4?4:0}" fontId="${i===1?1:0}" fillId="${i===1?2:i===3||i===5?3:0}" borderId="1" xfId="0" applyAlignment="1" applyFont="1" applyFill="1" applyBorder="1" applyNumberFormat="1"><alignment horizontal="${i>=4?'center':'right'}" vertical="center" wrapText="1" readingOrder="2"/></xf>`).join('')}</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 const column=i=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s};
 return files.map(([path,content])=>{
  if(path==='[Content_Types].xml')content=content.replace('</Types>','<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>');
  if(path==='xl/_rels/workbook.xml.rels')content=content.replace('</Relationships>','<Relationship Id="rStyles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');
  const match=path.match(/worksheets\/sheet(\d+)\.xml$/);
  if(match){const sheet=sheets[Number(match[1])-1],cols=sheet.rows[0]?.length||1;
   const widths=Array.from({length:cols},(_,i)=>Math.max(14,Math.min(40,Math.max(...sheet.rows.slice(0,200).map(row=>String(row[i]??'').length))+3)));
   content=content.replace('</sheetViews>','</sheetViews><sheetFormatPr defaultRowHeight="24"/><cols>'+widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')+'</cols>');
   content=content.replace(/<row r="(\d+)">([\s\S]*?)<\/row>/g,(_,row,cells)=>`<row r="${row}"${row==='1'?' ht="30" customHeight="1"':''}>${cells.replace(/<c r="([A-Z]+\d+)"(.*?)>/g,(_,ref,attrs)=>{let col=0;for(const letter of ref.replace(/\d/g,''))col=col*26+letter.charCodeAt(0)-64;const money=String(sheet.rows[0][col-1]||'').includes('MRU');return `<c r="${ref}"${attrs} s="${row==='1'?1:!attrs.includes('inlineStr')&&money?(Number(row)%2?5:4):(Number(row)%2?3:2)}">`})}</row>`);
   content=content.replace('</sheetData>',`</sheetData><autoFilter ref="A1:${column(cols-1)}${sheet.rows.length}"/><pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="9" fitToWidth="1" fitToHeight="0"/>`);
  }return [path,content];
 }).concat([['xl/styles.xml',styles]]);
}
